export type ProductClassificationRule = {
  id: string;
  group: "상의" | "아우터" | "하의" | "신발" | "가방" | "모자" | "액세서리";
  label: string;
  keywords: string[];
  attributes: {
    category: string;
    subCategory: string;
    detailCategory: string;
    material?: string;
    styleTags?: string[];
  };
};

// 구체적인 상품명이 먼저 오도록 정렬합니다. 새 분류는 이 테이블에만 추가합니다.
export const PRODUCT_CLASSIFICATION_RULES: ProductClassificationRule[] = [
  {
    id: "knit-cardigan",
    group: "아우터",
    label: "니트 가디건",
    keywords: ["니트 가디건", "knit cardigan"],
    attributes: {
      category: "아우터",
      subCategory: "가디건",
      detailCategory: "니트 가디건",
      material: "니트",
      styleTags: ["미니멀", "깔끔함"],
    },
  },
  {
    id: "windbreaker",
    group: "아우터",
    label: "바람막이",
    keywords: ["바람막이", "윈드브레이커", "windbreaker", "wind breaker"],
    attributes: {
      category: "아우터",
      subCategory: "자켓",
      detailCategory: "바람막이",
      styleTags: ["고프코어", "스포티"],
    },
  },
  {
    id: "ma-1",
    group: "아우터",
    label: "MA-1",
    keywords: ["ma-1", "ma 1", "엠에이원", "항공 점퍼", "항공점퍼"],
    attributes: {
      category: "아우터",
      subCategory: "점퍼",
      detailCategory: "MA-1",
      styleTags: ["스트릿", "워크웨어"],
    },
  },
  {
    id: "blouson",
    group: "아우터",
    label: "블루종",
    keywords: ["블루종", "blouson"],
    attributes: {
      category: "아우터",
      subCategory: "점퍼",
      detailCategory: "블루종",
      styleTags: ["캐주얼", "미니멀"],
    },
  },
  {
    id: "trucker-jacket",
    group: "아우터",
    label: "트러커 자켓",
    keywords: [
      "트러커 자켓",
      "트러커 재킷",
      "데님 트러커",
      "trucker jacket",
    ],
    attributes: {
      category: "아우터",
      subCategory: "자켓",
      detailCategory: "트러커 자켓",
      material: "데님",
      styleTags: ["캐주얼", "워크웨어"],
    },
  },
  {
    id: "denim-jacket",
    group: "아우터",
    label: "데님 자켓",
    keywords: ["데님 자켓", "데님 재킷", "denim jacket"],
    attributes: {
      category: "아우터",
      subCategory: "자켓",
      detailCategory: "데님 자켓",
      material: "데님",
      styleTags: ["캐주얼", "데일리"],
    },
  },
  {
    id: "leather-jacket",
    group: "아우터",
    label: "레더 자켓",
    keywords: ["레더 자켓", "레더 재킷", "가죽 자켓", "가죽 재킷", "leather jacket"],
    attributes: {
      category: "아우터",
      subCategory: "자켓",
      detailCategory: "레더 자켓",
      material: "가죽",
      styleTags: ["스트릿", "클래식"],
    },
  },
  {
    id: "fleece-jacket",
    group: "아우터",
    label: "플리스",
    keywords: ["플리스", "후리스", "fleece"],
    attributes: {
      category: "아우터",
      subCategory: "자켓",
      detailCategory: "플리스 자켓",
      material: "플리스",
      styleTags: ["캐주얼", "고프코어"],
    },
  },
  {
    id: "hoodie-zip-up",
    group: "아우터",
    label: "후드 집업",
    keywords: ["후드 집업", "후드집업", "zip up hoodie", "zip-up hoodie"],
    attributes: {
      category: "아우터",
      subCategory: "집업",
      detailCategory: "후드 집업",
      styleTags: ["캐주얼", "편안함"],
    },
  },
  {
    id: "padding-jacket",
    group: "아우터",
    label: "패딩",
    keywords: ["패딩", "다운 자켓", "다운 재킷", "puffer", "down jacket"],
    attributes: {
      category: "아우터",
      subCategory: "패딩",
      detailCategory: "패딩",
      styleTags: ["캐주얼", "스포티"],
    },
  },
  {
    id: "blazer",
    group: "아우터",
    label: "블레이저",
    keywords: ["블레이저", "blazer"],
    attributes: {
      category: "아우터",
      subCategory: "자켓",
      detailCategory: "블레이저",
      styleTags: ["미니멀", "포멀"],
    },
  },
  {
    id: "coat",
    group: "아우터",
    label: "코트",
    keywords: ["코트", "coat"],
    attributes: {
      category: "아우터",
      subCategory: "코트",
      detailCategory: "코트",
      styleTags: ["클래식", "깔끔함"],
    },
  },
  {
    id: "denim-shirt",
    group: "상의",
    label: "데님 셔츠",
    keywords: ["데님 셔츠", "denim shirt"],
    attributes: {
      category: "상의",
      subCategory: "셔츠",
      detailCategory: "데님 셔츠",
      material: "데님",
      styleTags: ["캐주얼", "데일리"],
    },
  },
  {
    id: "linen-shirt",
    group: "상의",
    label: "린넨 셔츠",
    keywords: ["린넨 셔츠", "linen shirt"],
    attributes: {
      category: "상의",
      subCategory: "셔츠",
      detailCategory: "린넨 셔츠",
      material: "린넨",
      styleTags: ["미니멀", "데일리"],
    },
  },
  {
    id: "flannel-shirt",
    group: "상의",
    label: "플란넬 셔츠",
    keywords: ["플란넬 셔츠", "flannel shirt"],
    attributes: {
      category: "상의",
      subCategory: "셔츠",
      detailCategory: "플란넬 셔츠",
      material: "플란넬",
      styleTags: ["캐주얼", "아메카지"],
    },
  },
  {
    id: "oxford-shirt",
    group: "상의",
    label: "옥스포드 셔츠",
    keywords: ["옥스포드 셔츠", "oxford shirt"],
    attributes: {
      category: "상의",
      subCategory: "셔츠",
      detailCategory: "옥스포드 셔츠",
      styleTags: ["미니멀", "깔끔함"],
    },
  },
  {
    id: "short-sleeve-knit",
    group: "상의",
    label: "반팔 니트",
    keywords: [
      "반팔 니트",
      "반소매 니트",
      "short sleeve knit",
      "short sleeved knit",
      "half sleeve knit",
    ],
    attributes: {
      category: "상의",
      subCategory: "니트",
      detailCategory: "반팔 니트",
      material: "니트",
      styleTags: ["미니멀", "깔끔함"],
    },
  },
  {
    id: "sleeveless-top",
    group: "상의",
    label: "민소매 티셔츠",
    keywords: [
      "민소매 티셔츠",
      "민소매 탑",
      "슬리브리스 티셔츠",
      "슬리브리스 탑",
      "나시 티셔츠",
      "탱크탑",
      "sleeveless t-shirt",
      "sleeveless tee",
      "sleeveless top",
      "tank top",
    ],
    attributes: {
      category: "상의",
      subCategory: "티셔츠",
      detailCategory: "민소매 티셔츠",
      styleTags: ["캐주얼", "데일리"],
    },
  },
  {
    id: "short-sleeve-t-shirt",
    group: "상의",
    label: "반팔 티셔츠",
    keywords: [
      "반팔 티셔츠",
      "반소매 티셔츠",
      "숏슬리브 티셔츠",
      "숏 슬리브 티셔츠",
      "short sleeve t-shirt",
      "short sleeve tee",
      "short-sleeve t-shirt",
      "short-sleeve tee",
    ],
    attributes: {
      category: "상의",
      subCategory: "티셔츠",
      detailCategory: "반팔 티셔츠",
      styleTags: ["캐주얼", "데일리"],
    },
  },
  {
    id: "long-sleeve-t-shirt",
    group: "상의",
    label: "긴팔 티셔츠",
    keywords: [
      "긴팔 티셔츠",
      "롱슬리브 티셔츠",
      "롱 슬리브 티셔츠",
      "long sleeve t-shirt",
      "long sleeve tee",
      "long-sleeve t-shirt",
      "long-sleeve tee",
    ],
    attributes: {
      category: "상의",
      subCategory: "티셔츠",
      detailCategory: "긴팔 티셔츠",
      styleTags: ["캐주얼", "데일리"],
    },
  },
  {
    id: "balloon-pants",
    group: "하의",
    label: "벌룬 팬츠",
    keywords: [
      "벌룬 팬츠",
      "벌룬팬츠",
      "벌룬 핏 팬츠",
      "벌룬핏 팬츠",
      "볼륨 팬츠",
      "볼륨팬츠",
      "balloon pants",
      "balloon fit pants",
      "volume pants",
    ],
    attributes: {
      category: "하의",
      subCategory: "팬츠",
      detailCategory: "벌룬 팬츠",
      styleTags: ["캐주얼", "스트릿"],
    },
  },
  {
    id: "barrel-pants",
    group: "하의",
    label: "배럴 팬츠",
    keywords: [
      "배럴 팬츠",
      "배럴팬츠",
      "배럴 레그 팬츠",
      "배럴레그 팬츠",
      "barrel pants",
      "barrel leg pants",
    ],
    attributes: {
      category: "하의",
      subCategory: "팬츠",
      detailCategory: "배럴 팬츠",
      styleTags: ["캐주얼", "모던"],
    },
  },
  {
    id: "curved-pants",
    group: "하의",
    label: "커브드 팬츠",
    keywords: [
      "커브드 팬츠",
      "커브 팬츠",
      "커브드핏 팬츠",
      "커브드 핏 팬츠",
      "curved pants",
      "curve pants",
      "curved fit pants",
    ],
    attributes: {
      category: "하의",
      subCategory: "팬츠",
      detailCategory: "커브드 팬츠",
      styleTags: ["캐주얼", "미니멀"],
    },
  },
  {
    id: "pleated-skirt",
    group: "하의",
    label: "플리츠 스커트",
    keywords: ["플리츠 스커트", "플리츠스커트", "pleated skirt", "pleats skirt"],
    attributes: {
      category: "하의",
      subCategory: "스커트",
      detailCategory: "플리츠 스커트",
      styleTags: ["클래식", "페미닌"],
    },
  },
  {
    id: "a-line-skirt",
    group: "하의",
    label: "A라인 스커트",
    keywords: ["A라인 스커트", "A라인스커트", "A-line skirt", "aline skirt"],
    attributes: {
      category: "하의",
      subCategory: "스커트",
      detailCategory: "A라인 스커트",
      styleTags: ["페미닌", "데일리"],
    },
  },
  {
    id: "mini-skirt",
    group: "하의",
    label: "미니 스커트",
    keywords: ["미니 스커트", "미니스커트", "mini skirt"],
    attributes: {
      category: "하의",
      subCategory: "스커트",
      detailCategory: "미니 스커트",
      styleTags: ["캐주얼", "데일리"],
    },
  },
  {
    id: "midi-skirt",
    group: "하의",
    label: "미디 스커트",
    keywords: ["미디 스커트", "미디스커트", "midi skirt"],
    attributes: {
      category: "하의",
      subCategory: "스커트",
      detailCategory: "미디 스커트",
      styleTags: ["미니멀", "데일리"],
    },
  },
  {
    id: "long-skirt",
    group: "하의",
    label: "롱 스커트",
    keywords: [
      "롱 스커트",
      "롱스커트",
      "맥시 스커트",
      "맥시스커트",
      "long skirt",
      "maxi skirt",
    ],
    attributes: {
      category: "하의",
      subCategory: "스커트",
      detailCategory: "롱 스커트",
      styleTags: ["미니멀", "데일리"],
    },
  },
  {
    id: "denim-skirt",
    group: "하의",
    label: "데님 스커트",
    keywords: ["데님 스커트", "데님스커트", "청치마", "denim skirt"],
    attributes: {
      category: "하의",
      subCategory: "스커트",
      detailCategory: "데님 스커트",
      material: "데님",
      styleTags: ["캐주얼", "데일리"],
    },
  },
  {
    id: "wide-slacks",
    group: "하의",
    label: "와이드 슬랙스",
    keywords: ["와이드 슬랙스", "wide slacks", "wide trousers"],
    attributes: {
      category: "하의",
      subCategory: "슬랙스",
      detailCategory: "와이드 슬랙스",
      styleTags: ["미니멀", "모던"],
    },
  },
  {
    id: "wide-denim",
    group: "하의",
    label: "와이드 데님",
    keywords: ["와이드 데님", "와이드 청바지", "wide denim", "wide jeans"],
    attributes: {
      category: "하의",
      subCategory: "데님팬츠",
      detailCategory: "와이드 데님 팬츠",
      material: "데님",
      styleTags: ["캐주얼", "스트릿"],
    },
  },
  {
    id: "straight-denim",
    group: "하의",
    label: "스트레이트 데님",
    keywords: ["스트레이트 데님", "일자 데님", "straight denim", "straight jeans"],
    attributes: {
      category: "하의",
      subCategory: "데님팬츠",
      detailCategory: "스트레이트 데님 팬츠",
      material: "데님",
      styleTags: ["캐주얼", "데일리"],
    },
  },
  {
    id: "raw-denim",
    group: "하의",
    label: "생지 데님",
    keywords: ["생지 데님", "생지 청바지", "raw denim", "rigid denim"],
    attributes: {
      category: "하의",
      subCategory: "데님팬츠",
      detailCategory: "생지 데님 팬츠",
      material: "데님",
      styleTags: ["아메카지", "클래식"],
    },
  },
  {
    id: "washed-denim",
    group: "하의",
    label: "워싱 데님",
    keywords: ["워싱 데님", "워싱 청바지", "washed denim", "washed jeans"],
    attributes: {
      category: "하의",
      subCategory: "데님팬츠",
      detailCategory: "워싱 데님 팬츠",
      material: "데님",
      styleTags: ["캐주얼", "빈티지"],
    },
  },
  {
    id: "cargo-pants",
    group: "하의",
    label: "카고 팬츠",
    keywords: ["카고 팬츠", "카고팬츠", "cargo pants", "cargo trousers"],
    attributes: {
      category: "하의",
      subCategory: "팬츠",
      detailCategory: "카고 팬츠",
      styleTags: ["고프코어", "스트릿"],
    },
  },
  {
    id: "jogger-pants",
    group: "하의",
    label: "조거 팬츠",
    keywords: ["조거 팬츠", "조거팬츠", "jogger pants", "joggers"],
    attributes: {
      category: "하의",
      subCategory: "팬츠",
      detailCategory: "조거 팬츠",
      styleTags: ["스포티", "편안함"],
    },
  },
  {
    id: "chino-pants",
    group: "하의",
    label: "치노 팬츠",
    keywords: ["치노 팬츠", "치노팬츠", "치노 팬츠", "chino pants", "chinos"],
    attributes: {
      category: "하의",
      subCategory: "팬츠",
      detailCategory: "치노 팬츠",
      styleTags: ["미니멀", "데일리"],
    },
  },
  {
    id: "carpenter-pants",
    group: "하의",
    label: "카펜터 팬츠",
    keywords: ["카펜터 팬츠", "카펜터팬츠", "carpenter pants"],
    attributes: {
      category: "하의",
      subCategory: "팬츠",
      detailCategory: "카펜터 팬츠",
      styleTags: ["워크웨어", "아메카지"],
    },
  },
  {
    id: "parachute-pants",
    group: "하의",
    label: "파라슈트 팬츠",
    keywords: ["파라슈트 팬츠", "파라슈트팬츠", "parachute pants"],
    attributes: {
      category: "하의",
      subCategory: "팬츠",
      detailCategory: "파라슈트 팬츠",
      styleTags: ["스트릿", "고프코어"],
    },
  },
  {
    id: "training-pants",
    group: "하의",
    label: "트레이닝 팬츠",
    keywords: ["트레이닝 팬츠", "트레이닝팬츠", "track pants", "sweatpants"],
    attributes: {
      category: "하의",
      subCategory: "팬츠",
      detailCategory: "트레이닝 팬츠",
      styleTags: ["스포티", "편안함"],
    },
  },
  {
    id: "shorts",
    group: "하의",
    label: "반바지",
    keywords: ["반바지", "쇼츠", "shorts", "short pants"],
    attributes: {
      category: "하의",
      subCategory: "반바지",
      detailCategory: "반바지",
      styleTags: ["캐주얼", "편안함"],
    },
  },
  {
    id: "denim-pants",
    group: "하의",
    label: "데님 팬츠",
    keywords: ["데님 팬츠", "denim pants", "denim jeans", "청바지", "jeans"],
    attributes: {
      category: "하의",
      subCategory: "팬츠",
      detailCategory: "데님 팬츠",
      material: "데님",
      styleTags: ["캐주얼", "데일리"],
    },
  },
  {
    id: "linen-pants",
    group: "하의",
    label: "린넨 팬츠",
    keywords: ["린넨 팬츠", "linen pants", "linen trousers"],
    attributes: {
      category: "하의",
      subCategory: "팬츠",
      detailCategory: "린넨 팬츠",
      material: "린넨",
      styleTags: ["미니멀", "데일리"],
    },
  },
  {
    id: "slacks",
    group: "하의",
    label: "슬랙스",
    keywords: ["슬랙스", "slacks", "tailored trousers"],
    attributes: {
      category: "하의",
      subCategory: "팬츠",
      detailCategory: "슬랙스",
      styleTags: ["미니멀", "포멀"],
    },
  },
  {
    id: "slingback-shoes",
    group: "신발",
    label: "슬링백 슈즈",
    keywords: [
      "슬링백 슈즈",
      "슬링백 펌프스",
      "슬링백 힐",
      "슬링백 플랫",
      "slingback shoes",
      "slingback pumps",
      "slingback heels",
      "slingback flats",
    ],
    attributes: {
      category: "신발",
      subCategory: "구두",
      detailCategory: "슬링백 슈즈",
      styleTags: ["미니멀", "포멀"],
    },
  },
  {
    id: "running-shoes",
    group: "신발",
    label: "러닝화",
    keywords: ["러닝화", "러닝 슈즈", "running shoes", "running sneakers"],
    attributes: {
      category: "신발",
      subCategory: "운동화",
      detailCategory: "러닝화",
      styleTags: ["스포티", "고프코어"],
    },
  },
  {
    id: "sneakers",
    group: "신발",
    label: "스니커즈",
    keywords: ["스니커즈", "운동화", "sneakers", "sneaker"],
    attributes: {
      category: "신발",
      subCategory: "스니커즈",
      detailCategory: "스니커즈",
      styleTags: ["캐주얼", "데일리"],
    },
  },
  {
    id: "derby-shoes",
    group: "신발",
    label: "더비슈즈",
    keywords: ["더비슈즈", "더비 슈즈", "더비화", "derby shoes"],
    attributes: {
      category: "신발",
      subCategory: "구두",
      detailCategory: "더비슈즈",
      styleTags: ["포멀", "클래식"],
    },
  },
  {
    id: "loafers",
    group: "신발",
    label: "로퍼",
    keywords: ["로퍼", "loafer", "loafers"],
    attributes: {
      category: "신발",
      subCategory: "구두",
      detailCategory: "로퍼",
      styleTags: ["미니멀", "포멀"],
    },
  },
  {
    id: "chelsea-boots",
    group: "신발",
    label: "첼시부츠",
    keywords: ["첼시부츠", "첼시 부츠", "chelsea boots", "chelsea boot"],
    attributes: {
      category: "신발",
      subCategory: "부츠",
      detailCategory: "첼시부츠",
      styleTags: ["클래식", "미니멀"],
    },
  },
  {
    id: "boots",
    group: "신발",
    label: "부츠",
    keywords: ["부츠", "워커", "boots", "boot"],
    attributes: {
      category: "신발",
      subCategory: "부츠",
      detailCategory: "부츠",
      styleTags: ["클래식", "캐주얼"],
    },
  },
  {
    id: "slippers",
    group: "신발",
    label: "슬리퍼",
    keywords: ["슬리퍼", "슬라이드", "쪼리", "flip flop", "slides", "slippers"],
    attributes: {
      category: "신발",
      subCategory: "슬리퍼",
      detailCategory: "슬리퍼",
      styleTags: ["캐주얼", "편안함"],
    },
  },
  {
    id: "sandals",
    group: "신발",
    label: "샌들",
    keywords: ["샌들", "sandal", "sandals"],
    attributes: {
      category: "신발",
      subCategory: "샌들",
      detailCategory: "샌들",
      styleTags: ["캐주얼", "편안함"],
    },
  },
  {
    id: "waist-bag",
    group: "가방",
    label: "웨이스트백",
    keywords: [
      "벨트 백",
      "벨트백",
      "웨이스트백",
      "웨이스트 백",
      "힙색",
      "힙 백",
      "waist bag",
      "belt bag",
      "fanny pack",
    ],
    attributes: {
      category: "액세서리",
      subCategory: "가방",
      detailCategory: "웨이스트백",
      styleTags: ["캐주얼", "고프코어"],
    },
  },
  {
    id: "messenger-bag",
    group: "가방",
    label: "메신저백",
    keywords: ["메신저백", "메신저 백", "messenger bag"],
    attributes: {
      category: "액세서리",
      subCategory: "가방",
      detailCategory: "메신저백",
      styleTags: ["스트릿", "캐주얼"],
    },
  },
  {
    id: "shoulder-bag",
    group: "가방",
    label: "숄더백",
    keywords: ["숄더백", "숄더 백", "shoulder bag"],
    attributes: {
      category: "액세서리",
      subCategory: "가방",
      detailCategory: "숄더백",
      styleTags: ["데일리", "미니멀"],
    },
  },
  {
    id: "sling-bag",
    group: "가방",
    label: "슬링백",
    keywords: ["슬링백", "슬링 백", "sling bag"],
    attributes: {
      category: "액세서리",
      subCategory: "가방",
      detailCategory: "슬링백",
      styleTags: ["스포티", "고프코어"],
    },
  },
  {
    id: "crossbody-bag",
    group: "가방",
    label: "크로스백",
    keywords: ["크로스백", "crossbody bag", "cross bag"],
    attributes: {
      category: "액세서리",
      subCategory: "가방",
      detailCategory: "크로스백",
      styleTags: ["캐주얼", "데일리"],
    },
  },
  {
    id: "tote-bag",
    group: "가방",
    label: "토트백",
    keywords: ["토트백", "tote bag"],
    attributes: {
      category: "액세서리",
      subCategory: "가방",
      detailCategory: "토트백",
      styleTags: ["미니멀", "데일리"],
    },
  },
  {
    id: "backpack",
    group: "가방",
    label: "백팩",
    keywords: ["백팩", "backpack", "rucksack"],
    attributes: {
      category: "액세서리",
      subCategory: "가방",
      detailCategory: "백팩",
      styleTags: ["캐주얼", "스포티"],
    },
  },
  {
    id: "bucket-hat",
    group: "모자",
    label: "버킷햇",
    keywords: ["버킷햇", "버킷 햇", "bucket hat"],
    attributes: {
      category: "액세서리",
      subCategory: "모자",
      detailCategory: "버킷햇",
      styleTags: ["캐주얼", "스트릿"],
    },
  },
  {
    id: "ball-cap",
    group: "모자",
    label: "볼캡",
    keywords: ["볼캡", "baseball cap", "ball cap"],
    attributes: {
      category: "액세서리",
      subCategory: "모자",
      detailCategory: "볼캡",
      styleTags: ["캐주얼", "스트릿"],
    },
  },
  {
    id: "beanie",
    group: "모자",
    label: "비니",
    keywords: ["비니", "beanie"],
    attributes: {
      category: "액세서리",
      subCategory: "모자",
      detailCategory: "비니",
      styleTags: ["캐주얼", "스트릿"],
    },
  },
  {
    id: "watch",
    group: "액세서리",
    label: "시계",
    keywords: ["손목시계", "시계", "wristwatch", "watch"],
    attributes: {
      category: "액세서리",
      subCategory: "시계",
      detailCategory: "시계",
      styleTags: ["클래식", "미니멀"],
    },
  },
  {
    id: "glasses",
    group: "액세서리",
    label: "안경",
    keywords: ["안경", "아이웨어", "glasses", "eyewear"],
    attributes: {
      category: "액세서리",
      subCategory: "안경",
      detailCategory: "안경",
      styleTags: ["미니멀", "클래식"],
    },
  },
  {
    id: "necklace",
    group: "액세서리",
    label: "목걸이",
    keywords: ["목걸이", "네크리스", "necklace"],
    attributes: {
      category: "액세서리",
      subCategory: "주얼리",
      detailCategory: "목걸이",
      styleTags: ["모던", "미니멀"],
    },
  },
  {
    id: "bracelet",
    group: "액세서리",
    label: "팔찌",
    keywords: ["팔찌", "브레이슬릿", "bracelet"],
    attributes: {
      category: "액세서리",
      subCategory: "주얼리",
      detailCategory: "팔찌",
      styleTags: ["모던", "미니멀"],
    },
  },
  {
    id: "ring",
    group: "액세서리",
    label: "반지",
    keywords: ["반지", "핑거 링", "finger ring"],
    attributes: {
      category: "액세서리",
      subCategory: "주얼리",
      detailCategory: "반지",
      styleTags: ["모던", "미니멀"],
    },
  },
  {
    id: "belt",
    group: "액세서리",
    label: "벨트",
    keywords: ["벨트", "belt"],
    attributes: {
      category: "액세서리",
      subCategory: "벨트",
      detailCategory: "벨트",
      styleTags: ["미니멀", "클래식"],
    },
  },
  {
    id: "scarf",
    group: "액세서리",
    label: "스카프",
    keywords: ["스카프", "머플러", "scarf", "muffler"],
    attributes: {
      category: "액세서리",
      subCategory: "스카프",
      detailCategory: "스카프",
      styleTags: ["클래식", "미니멀"],
    },
  },
];

// 세부 규칙이 없을 때만 사용하는 보수적인 기본 분류입니다.
export const PRODUCT_CATEGORY_FALLBACK_RULES: ProductClassificationRule[] = [
  {
    id: "generic-outerwear",
    group: "아우터",
    label: "아우터",
    keywords: ["아우터", "outerwear"],
    attributes: {
      category: "아우터",
      subCategory: "아우터",
      detailCategory: "아우터",
    },
  },
  {
    id: "generic-jacket",
    group: "아우터",
    label: "자켓",
    keywords: ["자켓", "재킷", "jacket", "jackets"],
    attributes: {
      category: "아우터",
      subCategory: "자켓",
      detailCategory: "자켓",
    },
  },
  {
    id: "generic-cardigan",
    group: "아우터",
    label: "가디건",
    keywords: ["가디건", "cardigan", "cardigans"],
    attributes: {
      category: "아우터",
      subCategory: "가디건",
      detailCategory: "가디건",
    },
  },
  {
    id: "generic-jumper",
    group: "아우터",
    label: "점퍼",
    keywords: ["점퍼", "jumper"],
    attributes: {
      category: "아우터",
      subCategory: "점퍼",
      detailCategory: "점퍼",
    },
  },
  {
    id: "generic-zip-up",
    group: "아우터",
    label: "집업",
    keywords: ["집업", "zip up", "zip-up"],
    attributes: {
      category: "아우터",
      subCategory: "집업",
      detailCategory: "집업",
    },
  },
  {
    id: "generic-t-shirt",
    group: "상의",
    label: "티셔츠",
    keywords: ["티셔츠", "t shirt", "t-shirt"],
    attributes: {
      category: "상의",
      subCategory: "티셔츠",
      detailCategory: "티셔츠",
    },
  },
  {
    id: "generic-shirt",
    group: "상의",
    label: "셔츠",
    keywords: ["셔츠", "shirt", "shirts"],
    attributes: {
      category: "상의",
      subCategory: "셔츠",
      detailCategory: "셔츠",
    },
  },
  {
    id: "generic-blouse",
    group: "상의",
    label: "블라우스",
    keywords: ["블라우스", "blouse", "blouses"],
    attributes: {
      category: "상의",
      subCategory: "블라우스",
      detailCategory: "블라우스",
    },
  },
  {
    id: "generic-knit",
    group: "상의",
    label: "니트",
    keywords: ["니트", "knit", "sweater", "sweaters"],
    attributes: {
      category: "상의",
      subCategory: "니트",
      detailCategory: "니트",
      material: "니트",
    },
  },
  {
    id: "generic-sweatshirt",
    group: "상의",
    label: "맨투맨",
    keywords: ["맨투맨", "sweatshirt"],
    attributes: {
      category: "상의",
      subCategory: "맨투맨",
      detailCategory: "맨투맨",
    },
  },
  {
    id: "generic-hoodie",
    group: "상의",
    label: "후드티",
    keywords: ["후드", "hoodie", "hoodies"],
    attributes: {
      category: "상의",
      subCategory: "후드티",
      detailCategory: "후드티",
    },
  },
  {
    id: "generic-top",
    group: "상의",
    label: "상의",
    keywords: ["상의", "top", "tops"],
    attributes: {
      category: "상의",
      subCategory: "상의",
      detailCategory: "상의",
    },
  },
  {
    id: "generic-pants",
    group: "하의",
    label: "팬츠",
    keywords: ["팬츠", "바지", "pants", "trousers"],
    attributes: {
      category: "하의",
      subCategory: "팬츠",
      detailCategory: "팬츠",
    },
  },
  {
    id: "generic-skirt",
    group: "하의",
    label: "스커트",
    keywords: ["스커트", "skirt", "skirts"],
    attributes: {
      category: "하의",
      subCategory: "스커트",
      detailCategory: "스커트",
    },
  },
  {
    id: "generic-bottom",
    group: "하의",
    label: "하의",
    keywords: ["하의", "bottom", "bottoms"],
    attributes: {
      category: "하의",
      subCategory: "하의",
      detailCategory: "하의",
    },
  },
  {
    id: "generic-bag",
    group: "가방",
    label: "가방",
    keywords: ["가방", "bag", "bags"],
    attributes: {
      category: "액세서리",
      subCategory: "가방",
      detailCategory: "가방",
    },
  },
  {
    id: "generic-shoes",
    group: "신발",
    label: "신발",
    keywords: ["신발", "shoes", "shoe", "footwear"],
    attributes: {
      category: "신발",
      subCategory: "신발",
      detailCategory: "신발",
    },
  },
  {
    id: "generic-hat",
    group: "모자",
    label: "모자",
    keywords: ["모자", "hat", "hats"],
    attributes: {
      category: "액세서리",
      subCategory: "모자",
      detailCategory: "모자",
    },
  },
  {
    id: "generic-accessory",
    group: "액세서리",
    label: "액세서리",
    keywords: ["액세서리", "accessory", "accessories"],
    attributes: {
      category: "액세서리",
      subCategory: "액세서리",
      detailCategory: "액세서리",
    },
  },
];
