export type ProductClassificationGroup =
  | "상의"
  | "아우터"
  | "하의"
  | "신발"
  | "가방"
  | "모자"
  | "액세서리";

export type ProductClassificationRule = {
  id: string;
  group: ProductClassificationGroup;
  label: string;
  keywords: string[];
  excludedKeywords?: string[];
  requiredKeywords?: string[];
  priority?: number;
  overridesCategoryGroup?: boolean;
  attributes: {
    category: string;
    subCategory: string;
    detailCategory: string;
    material?: string;
    styleTags?: string[];
  };
};

type ProductClassificationRuleSeed = Omit<
  ProductClassificationRule,
  "label" | "attributes"
> & {
  detailCategory: string;
  subCategory: string;
  category?: string;
  material?: string;
  styleTags?: string[];
};

function defineProductRule({
  detailCategory,
  subCategory,
  category,
  material,
  styleTags,
  ...rule
}: ProductClassificationRuleSeed): ProductClassificationRule {
  return {
    ...rule,
    label: detailCategory,
    attributes: {
      category: category || (rule.group === "가방" || rule.group === "모자" ? "액세서리" : rule.group),
      subCategory,
      detailCategory,
      ...(material ? { material } : {}),
      ...(styleTags ? { styleTags } : {}),
    },
  };
}

// 구체적인 상품명이 먼저 오도록 정렬합니다. 새 분류는 이 테이블에만 추가합니다.
export const PRODUCT_CLASSIFICATION_RULES: ProductClassificationRule[] = [
  defineProductRule({
    id: "tailored-jacket",
    group: "아우터",
    detailCategory: "테일러드 자켓",
    subCategory: "자켓",
    keywords: ["테일러드 자켓", "테일러드 재킷", "tailored jacket", "tailored jackets"],
    styleTags: ["포멀", "클래식"],
    priority: 20,
  }),
  defineProductRule({
    id: "bomber-jacket",
    group: "아우터",
    detailCategory: "봄버 자켓",
    subCategory: "점퍼",
    keywords: ["봄버 자켓", "봄버 재킷", "봄버 점퍼", "bomber jacket", "bomber jackets"],
    styleTags: ["캐주얼", "스트릿"],
    priority: 20,
  }),
  defineProductRule({
    id: "varsity-jacket",
    group: "아우터",
    detailCategory: "바시티 자켓",
    subCategory: "자켓",
    keywords: ["바시티 자켓", "바시티 재킷", "스타디움 자켓", "varsity jacket", "letterman jacket"],
    styleTags: ["캐주얼", "스트릿"],
    priority: 20,
  }),
  defineProductRule({
    id: "coach-jacket",
    group: "아우터",
    detailCategory: "코치 자켓",
    subCategory: "자켓",
    keywords: ["코치 자켓", "코치 재킷", "coach jacket", "coach jackets"],
    styleTags: ["캐주얼", "스트릿"],
    priority: 20,
  }),
  defineProductRule({
    id: "track-jacket",
    group: "아우터",
    detailCategory: "트랙 자켓",
    subCategory: "자켓",
    keywords: ["트랙 자켓", "트랙 재킷", "트레이닝 자켓", "track jacket", "track top"],
    styleTags: ["스포티", "캐주얼"],
    priority: 20,
  }),
  defineProductRule({
    id: "anorak",
    group: "아우터",
    detailCategory: "아노락",
    subCategory: "점퍼",
    keywords: ["아노락", "아노락 자켓", "anorak", "anorak jacket"],
    styleTags: ["고프코어", "스포티"],
    priority: 20,
  }),
  defineProductRule({
    id: "chore-jacket",
    group: "아우터",
    detailCategory: "초어 자켓",
    subCategory: "자켓",
    keywords: ["초어 자켓", "초어 재킷", "chore jacket", "chore coat"],
    styleTags: ["워크웨어", "아메카지"],
    priority: 20,
  }),
  defineProductRule({
    id: "hunting-jacket",
    group: "아우터",
    detailCategory: "헌팅 자켓",
    subCategory: "자켓",
    keywords: ["헌팅 자켓", "헌팅 재킷", "hunting jacket", "hunting coat"],
    styleTags: ["아메카지", "워크웨어"],
    priority: 20,
  }),
  defineProductRule({
    id: "m65-jacket",
    group: "아우터",
    detailCategory: "M-65 자켓",
    subCategory: "자켓",
    keywords: ["M-65 자켓", "M65 자켓", "엠육오 자켓", "m-65 jacket", "m65 field jacket"],
    styleTags: ["아메카지", "워크웨어"],
    priority: 30,
  }),
  defineProductRule({
    id: "field-jacket",
    group: "아우터",
    detailCategory: "필드 자켓",
    subCategory: "자켓",
    keywords: ["필드 자켓", "필드 재킷", "field jacket", "field coat"],
    styleTags: ["아메카지", "워크웨어"],
    priority: 20,
  }),
  defineProductRule({
    id: "safari-jacket",
    group: "아우터",
    detailCategory: "사파리 자켓",
    subCategory: "자켓",
    keywords: ["사파리 자켓", "사파리 재킷", "safari jacket", "safari coat"],
    styleTags: ["클래식", "아메카지"],
    priority: 20,
  }),
  defineProductRule({
    id: "harrington-jacket",
    group: "아우터",
    detailCategory: "해링턴 자켓",
    subCategory: "자켓",
    keywords: ["해링턴 자켓", "해링턴 재킷", "harrington jacket", "harrington jackets"],
    styleTags: ["클래식", "캐주얼"],
    priority: 20,
  }),
  defineProductRule({
    id: "suede-jacket",
    group: "아우터",
    detailCategory: "스웨이드 자켓",
    subCategory: "자켓",
    keywords: ["스웨이드 자켓", "스웨이드 재킷", "suede jacket", "suede jackets"],
    material: "스웨이드",
    styleTags: ["클래식", "빈티지"],
    priority: 20,
  }),
  defineProductRule({
    id: "rider-jacket",
    group: "아우터",
    detailCategory: "라이더 자켓",
    subCategory: "자켓",
    keywords: ["라이더 자켓", "라이더 재킷", "바이커 자켓", "rider jacket", "biker jacket"],
    material: "가죽",
    styleTags: ["스트릿", "빈티지"],
    priority: 25,
  }),
  defineProductRule({
    id: "trench-coat",
    group: "아우터",
    detailCategory: "트렌치코트",
    subCategory: "코트",
    keywords: ["트렌치코트", "트렌치 코트", "trench coat", "trench coats"],
    styleTags: ["클래식", "포멀"],
    priority: 20,
  }),
  defineProductRule({
    id: "mac-coat",
    group: "아우터",
    detailCategory: "맥코트",
    subCategory: "코트",
    keywords: ["맥코트", "맥 코트", "mac coat", "mackintosh coat"],
    styleTags: ["미니멀", "클래식"],
    priority: 20,
  }),
  defineProductRule({
    id: "balmacaan-coat",
    group: "아우터",
    detailCategory: "발마칸 코트",
    subCategory: "코트",
    keywords: ["발마칸 코트", "발마칸코트", "balmacaan coat", "balmacaan overcoat"],
    styleTags: ["클래식", "미니멀"],
    priority: 20,
  }),
  defineProductRule({
    id: "chesterfield-coat",
    group: "아우터",
    detailCategory: "체스터필드 코트",
    subCategory: "코트",
    keywords: ["체스터필드 코트", "체스터 코트", "chesterfield coat", "chesterfield overcoat"],
    styleTags: ["포멀", "클래식"],
    priority: 20,
  }),
  defineProductRule({
    id: "duffle-coat",
    group: "아우터",
    detailCategory: "더플코트",
    subCategory: "코트",
    keywords: ["더플코트", "더플 코트", "duffle coat", "duffel coat"],
    styleTags: ["클래식", "캐주얼"],
    priority: 20,
  }),
  defineProductRule({
    id: "pea-coat",
    group: "아우터",
    detailCategory: "피코트",
    subCategory: "코트",
    keywords: ["피코트", "피 코트", "pea coat", "peacoat"],
    styleTags: ["클래식", "포멀"],
    priority: 20,
  }),
  defineProductRule({
    id: "single-coat",
    group: "아우터",
    detailCategory: "싱글 코트",
    subCategory: "코트",
    keywords: ["싱글 코트", "싱글코트", "single coat", "single breasted coat"],
    styleTags: ["미니멀", "포멀"],
    priority: 15,
  }),
  defineProductRule({
    id: "double-coat",
    group: "아우터",
    detailCategory: "더블 코트",
    subCategory: "코트",
    keywords: ["더블 코트", "더블코트", "double coat", "double breasted coat"],
    styleTags: ["클래식", "포멀"],
    priority: 15,
  }),
  defineProductRule({
    id: "long-coat",
    group: "아우터",
    detailCategory: "롱코트",
    subCategory: "코트",
    keywords: ["롱코트", "롱 코트", "long coat", "long overcoat"],
    styleTags: ["미니멀", "클래식"],
    priority: 10,
  }),
  defineProductRule({
    id: "short-coat",
    group: "아우터",
    detailCategory: "숏코트",
    subCategory: "코트",
    keywords: ["숏코트", "숏 코트", "short coat", "cropped coat"],
    styleTags: ["모던", "미니멀"],
    priority: 10,
  }),
  defineProductRule({
    id: "fishtail-parka",
    group: "아우터",
    detailCategory: "피시테일 파카",
    subCategory: "점퍼",
    keywords: ["피시테일 파카", "피쉬테일 파카", "fishtail parka", "fish tail parka"],
    styleTags: ["아메카지", "고프코어"],
    priority: 25,
  }),
  defineProductRule({
    id: "raincoat",
    group: "아우터",
    detailCategory: "레인코트",
    subCategory: "코트",
    keywords: ["레인코트", "우비", "raincoat", "rain coat"],
    styleTags: ["고프코어", "캐주얼"],
    priority: 20,
  }),
  defineProductRule({
    id: "parka",
    group: "아우터",
    detailCategory: "파카",
    subCategory: "점퍼",
    keywords: ["파카", "parka", "parkas"],
    styleTags: ["캐주얼", "고프코어"],
    priority: 5,
  }),
  defineProductRule({
    id: "short-padding",
    group: "아우터",
    detailCategory: "숏패딩",
    subCategory: "패딩",
    keywords: ["숏패딩", "숏 패딩", "short puffer jacket", "cropped puffer jacket"],
    styleTags: ["캐주얼", "스포티"],
    priority: 25,
  }),
  defineProductRule({
    id: "long-padding",
    group: "아우터",
    detailCategory: "롱패딩",
    subCategory: "패딩",
    keywords: ["롱패딩", "롱 패딩", "long puffer coat", "long padded coat"],
    styleTags: ["캐주얼", "스포티"],
    priority: 25,
  }),
  defineProductRule({
    id: "down-jacket",
    group: "아우터",
    detailCategory: "다운 자켓",
    subCategory: "패딩",
    keywords: ["다운 자켓", "다운 재킷", "down jacket", "down puffer jacket"],
    styleTags: ["캐주얼", "고프코어"],
    priority: 25,
  }),
  defineProductRule({
    id: "quilted-jacket",
    group: "아우터",
    detailCategory: "퀼팅 자켓",
    subCategory: "자켓",
    keywords: ["퀼팅 자켓", "퀼팅 재킷", "누빔 자켓", "quilted jacket", "quilt jacket"],
    styleTags: ["클래식", "캐주얼"],
    priority: 20,
  }),
  defineProductRule({
    id: "padded-vest",
    group: "아우터",
    detailCategory: "패딩 베스트",
    subCategory: "베스트",
    keywords: ["패딩 베스트", "패딩 조끼", "padded vest", "puffer vest"],
    styleTags: ["캐주얼", "고프코어"],
    priority: 25,
  }),
  defineProductRule({
    id: "down-vest",
    group: "아우터",
    detailCategory: "다운 베스트",
    subCategory: "베스트",
    keywords: ["다운 베스트", "다운 조끼", "down vest", "down gilet"],
    styleTags: ["캐주얼", "고프코어"],
    priority: 25,
  }),
  defineProductRule({
    id: "fleece-vest",
    group: "아우터",
    detailCategory: "플리스 베스트",
    subCategory: "베스트",
    keywords: ["플리스 베스트", "후리스 조끼", "fleece vest", "fleece gilet"],
    material: "플리스",
    styleTags: ["캐주얼", "고프코어"],
    priority: 25,
  }),
  defineProductRule({
    id: "shearling-jacket",
    group: "아우터",
    detailCategory: "무스탕",
    subCategory: "자켓",
    keywords: ["무스탕", "무스탕 자켓", "shearling jacket", "shearling coat"],
    styleTags: ["클래식", "빈티지"],
    priority: 20,
  }),
  {
    id: "knit-zip-up",
    group: "아우터",
    label: "니트 집업",
    keywords: [
      "니트 집업",
      "집업 니트",
      "니트 가디건 집업",
      "니트 카디건 집업",
      "케이블 집업",
      "knit zip up",
      "knit zip cardigan",
      "knitted zip cardigan",
      "zip knit cardigan",
      "cable knit zip",
    ],
    overridesCategoryGroup: true,
    attributes: {
      category: "아우터",
      subCategory: "집업",
      detailCategory: "니트 집업",
      material: "니트",
      styleTags: ["미니멀", "깔끔함"],
    },
  },
  {
    id: "knit-cardigan",
    group: "아우터",
    label: "니트 가디건",
    keywords: ["니트 가디건", "knit cardigan"],
    attributes: {
      category: "아우터",
      subCategory: "가디건",
      detailCategory: "니트 가디건",
      material: "니트",
      styleTags: ["미니멀", "깔끔함"],
    },
  },
  {
    id: "windbreaker",
    group: "아우터",
    label: "바람막이",
    keywords: ["바람막이", "윈드브레이커", "windbreaker", "wind breaker"],
    attributes: {
      category: "아우터",
      subCategory: "자켓",
      detailCategory: "바람막이",
      styleTags: ["고프코어", "스포티"],
    },
  },
  {
    id: "ma-1",
    group: "아우터",
    label: "MA-1",
    keywords: ["ma-1", "엠에이원", "항공 점퍼", "항공점퍼"],
    attributes: {
      category: "아우터",
      subCategory: "점퍼",
      detailCategory: "MA-1",
      styleTags: ["스트릿", "워크웨어"],
    },
  },
  {
    id: "blouson",
    group: "아우터",
    label: "블루종",
    keywords: ["블루종", "blouson"],
    attributes: {
      category: "아우터",
      subCategory: "점퍼",
      detailCategory: "블루종",
      styleTags: ["캐주얼", "미니멀"],
    },
  },
  {
    id: "trucker-jacket",
    group: "아우터",
    label: "트러커 자켓",
    keywords: [
      "트러커 자켓",
      "트러커 재킷",
      "데님 트러커",
      "trucker jacket",
    ],
    attributes: {
      category: "아우터",
      subCategory: "자켓",
      detailCategory: "트러커 자켓",
      material: "데님",
      styleTags: ["캐주얼", "워크웨어"],
    },
  },
  {
    id: "denim-jacket",
    group: "아우터",
    label: "데님 자켓",
    keywords: ["데님 자켓", "데님 재킷", "denim jacket"],
    attributes: {
      category: "아우터",
      subCategory: "자켓",
      detailCategory: "데님 자켓",
      material: "데님",
      styleTags: ["캐주얼", "데일리"],
    },
  },
  {
    id: "leather-jacket",
    group: "아우터",
    label: "레더 자켓",
    keywords: ["레더 자켓", "레더 재킷", "가죽 자켓", "가죽 재킷", "leather jacket"],
    attributes: {
      category: "아우터",
      subCategory: "자켓",
      detailCategory: "레더 자켓",
      material: "가죽",
      styleTags: ["스트릿", "클래식"],
    },
  },
  {
    id: "fleece-jacket",
    group: "아우터",
    label: "플리스",
    keywords: ["플리스", "후리스", "fleece"],
    attributes: {
      category: "아우터",
      subCategory: "자켓",
      detailCategory: "플리스 자켓",
      material: "플리스",
      styleTags: ["캐주얼", "고프코어"],
    },
  },
  {
    id: "hoodie-zip-up",
    group: "아우터",
    label: "후드 집업",
    keywords: ["후드 집업", "후드집업", "zip-up hoodie"],
    attributes: {
      category: "아우터",
      subCategory: "집업",
      detailCategory: "후드 집업",
      styleTags: ["캐주얼", "편안함"],
    },
  },
  {
    id: "padding-jacket",
    group: "아우터",
    label: "패딩",
    keywords: ["패딩", "puffer", "padded jacket"],
    attributes: {
      category: "아우터",
      subCategory: "패딩",
      detailCategory: "패딩",
      styleTags: ["캐주얼", "스포티"],
    },
  },
  {
    id: "blazer",
    group: "아우터",
    label: "블레이저",
    keywords: ["블레이저", "blazer"],
    attributes: {
      category: "아우터",
      subCategory: "자켓",
      detailCategory: "블레이저",
      styleTags: ["미니멀", "포멀"],
    },
  },
  {
    id: "coat",
    group: "아우터",
    label: "코트",
    keywords: ["코트", "coat"],
    attributes: {
      category: "아우터",
      subCategory: "코트",
      detailCategory: "코트",
      styleTags: ["클래식", "깔끔함"],
    },
  },
  {
    id: "shacket",
    group: "아우터",
    label: "셔켓",
    keywords: [
      "셔켓",
      "셔츠 자켓",
      "셔츠 재킷",
      "shirt jacket",
      "shacket",
    ],
    overridesCategoryGroup: true,
    attributes: {
      category: "아우터",
      subCategory: "자켓",
      detailCategory: "셔켓",
      styleTags: ["캐주얼", "워크웨어"],
    },
  },
  {
    id: "overshirt",
    group: "아우터",
    label: "오버셔츠",
    keywords: [
      "오버셔츠",
      "오버 셔츠",
      "overshirt",
      "over shirt",
    ],
    overridesCategoryGroup: true,
    attributes: {
      category: "아우터",
      subCategory: "자켓",
      detailCategory: "오버셔츠",
      styleTags: ["캐주얼", "데일리"],
    },
  },
  defineProductRule({
    id: "basic-t-shirt",
    group: "상의",
    detailCategory: "기본 티셔츠",
    subCategory: "티셔츠",
    keywords: ["기본 티셔츠", "베이직 티셔츠", "무지 티셔츠", "basic t-shirt", "basic tee", "plain t-shirt"],
    styleTags: ["데일리", "캐주얼"],
    priority: -10,
  }),
  defineProductRule({
    id: "tank-top",
    group: "상의",
    detailCategory: "탱크탑",
    subCategory: "티셔츠",
    keywords: ["탱크탑", "탱크 탑", "tank top", "tank tops"],
    styleTags: ["캐주얼", "스포티"],
    priority: 25,
  }),
  defineProductRule({
    id: "crop-top",
    group: "상의",
    detailCategory: "크롭탑",
    subCategory: "티셔츠",
    keywords: ["크롭탑", "크롭 탑", "크롭 티셔츠", "crop top", "cropped top", "cropped t-shirt"],
    styleTags: ["캐주얼", "모던"],
    priority: 20,
  }),
  defineProductRule({
    id: "v-neck-t-shirt",
    group: "상의",
    detailCategory: "브이넥 티셔츠",
    subCategory: "티셔츠",
    keywords: ["브이넥 티셔츠", "V넥 티셔츠", "v-neck t-shirt", "v neck tee"],
    styleTags: ["미니멀", "데일리"],
    priority: 20,
  }),
  defineProductRule({
    id: "henley-t-shirt",
    group: "상의",
    detailCategory: "헨리넥 티셔츠",
    subCategory: "티셔츠",
    keywords: ["헨리넥 티셔츠", "헨리넥 티", "henley t-shirt", "henley tee"],
    styleTags: ["캐주얼", "아메카지"],
    priority: 20,
  }),
  defineProductRule({
    id: "mock-neck-t-shirt",
    group: "상의",
    detailCategory: "모크넥 티셔츠",
    subCategory: "티셔츠",
    keywords: ["모크넥 티셔츠", "모크넥 티", "mock neck t-shirt", "mockneck tee"],
    styleTags: ["미니멀", "모던"],
    priority: 20,
  }),
  defineProductRule({
    id: "turtleneck-t-shirt",
    group: "상의",
    detailCategory: "터틀넥 티셔츠",
    subCategory: "티셔츠",
    keywords: ["터틀넥 티셔츠", "목폴라 티셔츠", "turtleneck t-shirt", "roll neck tee"],
    styleTags: ["미니멀", "클래식"],
    priority: 20,
  }),
  defineProductRule({
    id: "ringer-t-shirt",
    group: "상의",
    detailCategory: "링거 티셔츠",
    subCategory: "티셔츠",
    keywords: ["링거 티셔츠", "링거티", "ringer t-shirt", "ringer tee"],
    styleTags: ["캐주얼", "빈티지"],
    priority: 20,
  }),
  defineProductRule({
    id: "raglan-t-shirt",
    group: "상의",
    detailCategory: "래글런 티셔츠",
    subCategory: "티셔츠",
    keywords: ["래글런 티셔츠", "라글란 티셔츠", "raglan t-shirt", "raglan tee"],
    styleTags: ["캐주얼", "스포티"],
    priority: 20,
  }),
  defineProductRule({
    id: "polo-shirt",
    group: "상의",
    detailCategory: "폴로 셔츠",
    subCategory: "티셔츠",
    keywords: ["폴로 셔츠", "피케 셔츠", "피케 폴로", "polo shirt", "polo tee", "pique shirt", "pique polo"],
    styleTags: ["클래식", "캐주얼"],
    priority: 20,
  }),
  defineProductRule({
    id: "rugby-shirt",
    group: "상의",
    detailCategory: "럭비 셔츠",
    subCategory: "티셔츠",
    keywords: ["럭비 셔츠", "럭비 티셔츠", "rugby shirt", "rugby jersey"],
    styleTags: ["캐주얼", "스포티"],
    priority: 20,
  }),
  defineProductRule({
    id: "mesh-jersey",
    group: "상의",
    detailCategory: "메시 저지",
    subCategory: "티셔츠",
    keywords: ["메시 저지", "메쉬 저지", "mesh jersey", "mesh sports jersey"],
    styleTags: ["스포티", "스트릿"],
    priority: 25,
  }),
  defineProductRule({
    id: "sports-jersey",
    group: "상의",
    detailCategory: "스포츠 저지",
    subCategory: "티셔츠",
    keywords: ["스포츠 저지", "유니폼 저지", "sports jersey", "team jersey"],
    styleTags: ["스포티", "캐주얼"],
    priority: 20,
  }),
  defineProductRule({
    id: "dress-shirt",
    group: "상의",
    detailCategory: "드레스 셔츠",
    subCategory: "셔츠",
    keywords: ["드레스 셔츠", "정장 셔츠", "dress shirt", "formal shirt"],
    styleTags: ["포멀", "클래식"],
    priority: 20,
  }),
  defineProductRule({
    id: "western-shirt",
    group: "상의",
    detailCategory: "웨스턴 셔츠",
    subCategory: "셔츠",
    keywords: ["웨스턴 셔츠", "카우보이 셔츠", "western shirt", "cowboy shirt"],
    styleTags: ["아메카지", "빈티지"],
    priority: 20,
  }),
  defineProductRule({
    id: "camp-collar-shirt",
    group: "상의",
    detailCategory: "캠프칼라 셔츠",
    subCategory: "셔츠",
    keywords: ["캠프칼라 셔츠", "캠프 카라 셔츠", "camp collar shirt", "resort collar shirt"],
    styleTags: ["캐주얼", "데일리"],
    priority: 25,
  }),
  defineProductRule({
    id: "open-collar-shirt",
    group: "상의",
    detailCategory: "오픈칼라 셔츠",
    subCategory: "셔츠",
    keywords: ["오픈칼라 셔츠", "오픈 카라 셔츠", "open collar shirt"],
    styleTags: ["캐주얼", "미니멀"],
    priority: 20,
  }),
  defineProductRule({
    id: "cuban-shirt",
    group: "상의",
    detailCategory: "쿠반 셔츠",
    subCategory: "셔츠",
    keywords: ["쿠반 셔츠", "쿠바 셔츠", "cuban shirt", "cuban collar shirt"],
    styleTags: ["캐주얼", "빈티지"],
    priority: 20,
  }),
  defineProductRule({
    id: "hawaiian-shirt",
    group: "상의",
    detailCategory: "하와이안 셔츠",
    subCategory: "셔츠",
    keywords: ["하와이안 셔츠", "알로하 셔츠", "hawaiian shirt", "aloha shirt"],
    styleTags: ["캐주얼", "빈티지"],
    priority: 20,
  }),
  defineProductRule({
    id: "mandarin-collar-shirt",
    group: "상의",
    detailCategory: "차이나칼라 셔츠",
    subCategory: "셔츠",
    keywords: ["차이나칼라 셔츠", "차이나 카라 셔츠", "스탠드칼라 셔츠", "mandarin collar shirt", "band collar shirt"],
    styleTags: ["미니멀", "모던"],
    priority: 20,
  }),
  defineProductRule({
    id: "tunic-shirt",
    group: "상의",
    detailCategory: "튜닉 셔츠",
    subCategory: "셔츠",
    keywords: ["튜닉 셔츠", "롱 튜닉 셔츠", "tunic shirt", "shirt tunic"],
    styleTags: ["미니멀", "캐주얼"],
    priority: 20,
  }),
  defineProductRule({
    id: "basic-shirt",
    group: "상의",
    detailCategory: "기본 셔츠",
    subCategory: "셔츠",
    keywords: ["기본 셔츠", "베이직 셔츠", "basic shirt", "plain shirt"],
    styleTags: ["데일리", "미니멀"],
    priority: -10,
  }),
  defineProductRule({
    id: "basic-blouse",
    group: "상의",
    detailCategory: "기본 블라우스",
    subCategory: "블라우스",
    keywords: ["기본 블라우스", "베이직 블라우스", "basic blouse", "plain blouse"],
    styleTags: ["데일리", "미니멀"],
    priority: -10,
  }),
  defineProductRule({
    id: "tie-neck-blouse",
    group: "상의",
    detailCategory: "타이 블라우스",
    subCategory: "블라우스",
    keywords: ["타이 블라우스", "보우 블라우스", "tie neck blouse", "bow blouse"],
    styleTags: ["페미닌", "포멀"],
    priority: 20,
  }),
  defineProductRule({
    id: "puff-sleeve-blouse",
    group: "상의",
    detailCategory: "퍼프소매 블라우스",
    subCategory: "블라우스",
    keywords: ["퍼프소매 블라우스", "퍼프 블라우스", "puff sleeve blouse", "puffed sleeve blouse"],
    styleTags: ["페미닌", "러블리"],
    priority: 20,
  }),
  defineProductRule({
    id: "off-shoulder-blouse",
    group: "상의",
    detailCategory: "오프숄더 블라우스",
    subCategory: "블라우스",
    keywords: ["오프숄더 블라우스", "오프 숄더 블라우스", "off shoulder blouse"],
    styleTags: ["페미닌", "모던"],
    priority: 20,
  }),
  defineProductRule({
    id: "crewneck-knit",
    group: "상의",
    detailCategory: "크루넥 니트",
    subCategory: "니트",
    keywords: ["크루넥 니트", "라운드넥 니트", "crew neck knit", "crewneck sweater"],
    material: "니트",
    styleTags: ["미니멀", "데일리"],
    priority: 20,
  }),
  defineProductRule({
    id: "v-neck-knit",
    group: "상의",
    detailCategory: "브이넥 니트",
    subCategory: "니트",
    keywords: ["브이넥 니트", "V넥 니트", "v-neck knit", "v neck sweater"],
    material: "니트",
    styleTags: ["미니멀", "클래식"],
    priority: 20,
  }),
  defineProductRule({
    id: "turtleneck-knit",
    group: "상의",
    detailCategory: "터틀넥 니트",
    subCategory: "니트",
    keywords: ["터틀넥 니트", "목폴라 니트", "turtleneck knit", "roll neck sweater"],
    material: "니트",
    styleTags: ["미니멀", "클래식"],
    priority: 20,
  }),
  defineProductRule({
    id: "mock-neck-knit",
    group: "상의",
    detailCategory: "모크넥 니트",
    subCategory: "니트",
    keywords: ["모크넥 니트", "하이넥 니트", "mock neck knit", "mockneck sweater"],
    material: "니트",
    styleTags: ["미니멀", "모던"],
    priority: 20,
  }),
  defineProductRule({
    id: "knit-vest",
    group: "상의",
    detailCategory: "니트 베스트",
    subCategory: "니트",
    keywords: ["니트 베스트", "니트 조끼", "knit vest", "sweater vest"],
    material: "니트",
    styleTags: ["미니멀", "클래식"],
    priority: 20,
  }),
  defineProductRule({
    id: "cable-knit",
    group: "상의",
    detailCategory: "케이블 니트",
    subCategory: "니트",
    keywords: ["케이블 니트", "꽈배기 니트", "cable knit", "cable sweater"],
    material: "니트",
    styleTags: ["클래식", "캐주얼"],
    priority: 20,
  }),
  defineProductRule({
    id: "sweatshirt",
    group: "상의",
    detailCategory: "맨투맨",
    subCategory: "맨투맨",
    keywords: ["맨투맨", "스웨트셔츠", "sweatshirt", "crewneck sweatshirt"],
    styleTags: ["캐주얼", "편안함"],
    priority: 10,
  }),
  defineProductRule({
    id: "hoodie",
    group: "상의",
    detailCategory: "후드티",
    subCategory: "후드티",
    keywords: ["후드티", "후디", "hoodie", "pullover hoodie"],
    styleTags: ["캐주얼", "편안함"],
    excludedKeywords: ["집업", "zip up", "zip-up"],
    priority: 10,
  }),
  {
    id: "denim-shirt",
    group: "상의",
    label: "데님 셔츠",
    keywords: ["데님 셔츠", "denim shirt"],
    attributes: {
      category: "상의",
      subCategory: "셔츠",
      detailCategory: "데님 셔츠",
      material: "데님",
      styleTags: ["캐주얼", "데일리"],
    },
  },
  {
    id: "linen-shirt",
    group: "상의",
    label: "린넨 셔츠",
    keywords: ["린넨 셔츠", "linen shirt"],
    attributes: {
      category: "상의",
      subCategory: "셔츠",
      detailCategory: "린넨 셔츠",
      material: "린넨",
      styleTags: ["미니멀", "데일리"],
    },
  },
  {
    id: "flannel-shirt",
    group: "상의",
    label: "플란넬 셔츠",
    keywords: ["플란넬 셔츠", "flannel shirt"],
    attributes: {
      category: "상의",
      subCategory: "셔츠",
      detailCategory: "플란넬 셔츠",
      material: "플란넬",
      styleTags: ["캐주얼", "아메카지"],
    },
  },
  {
    id: "oxford-shirt",
    group: "상의",
    label: "옥스포드 셔츠",
    keywords: [
      "옥스포드 셔츠",
      "oxford shirt",
      "oxford short sleeve shirt",
      "oxford long sleeve shirt",
      "oxford cotton shirt",
      "oxford button down shirt",
    ],
    attributes: {
      category: "상의",
      subCategory: "셔츠",
      detailCategory: "옥스포드 셔츠",
      styleTags: ["미니멀", "깔끔함"],
    },
  },
  {
    id: "short-sleeve-knit",
    group: "상의",
    label: "반팔 니트",
    keywords: [
      "반팔 니트",
      "반소매 니트",
      "short sleeve knit",
      "short sleeved knit",
      "half sleeve knit",
    ],
    attributes: {
      category: "상의",
      subCategory: "니트",
      detailCategory: "반팔 니트",
      material: "니트",
      styleTags: ["미니멀", "깔끔함"],
    },
  },
  {
    id: "sleeveless-top",
    group: "상의",
    label: "민소매 티셔츠",
    keywords: [
      "민소매 티셔츠",
      "민소매 탑",
      "슬리브리스 티셔츠",
      "슬리브리스 탑",
      "나시 티셔츠",
      "sleeveless t-shirt",
      "sleeveless tee",
      "sleeveless top",
    ],
    attributes: {
      category: "상의",
      subCategory: "티셔츠",
      detailCategory: "민소매 티셔츠",
      styleTags: ["캐주얼", "데일리"],
    },
  },
  {
    id: "short-sleeve-t-shirt",
    group: "상의",
    label: "반팔 티셔츠",
    keywords: [
      "반팔 티셔츠",
      "반소매 티셔츠",
      "숏슬리브 티셔츠",
      "숏 슬리브 티셔츠",
      "short sleeve t-shirt",
      "short sleeve tee",
    ],
    attributes: {
      category: "상의",
      subCategory: "티셔츠",
      detailCategory: "반팔 티셔츠",
      styleTags: ["캐주얼", "데일리"],
    },
  },
  {
    id: "long-sleeve-t-shirt",
    group: "상의",
    label: "긴팔 티셔츠",
    keywords: [
      "긴팔 티셔츠",
      "롱슬리브 티셔츠",
      "롱 슬리브 티셔츠",
      "long sleeve t-shirt",
      "long sleeve tee",
    ],
    attributes: {
      category: "상의",
      subCategory: "티셔츠",
      detailCategory: "긴팔 티셔츠",
      styleTags: ["캐주얼", "데일리"],
    },
  },
  defineProductRule({
    id: "one-tuck-pants",
    group: "하의",
    detailCategory: "원턱 팬츠",
    subCategory: "팬츠",
    keywords: ["원턱 팬츠", "원 턱 팬츠", "1턱 팬츠", "one tuck pants", "single pleat trousers"],
    styleTags: ["미니멀", "클래식"],
    priority: 5,
  }),
  defineProductRule({
    id: "two-tuck-pants",
    group: "하의",
    detailCategory: "투턱 팬츠",
    subCategory: "팬츠",
    keywords: ["투턱 팬츠", "투 턱 팬츠", "2턱 팬츠", "two tuck pants", "double pleat trousers"],
    styleTags: ["미니멀", "클래식"],
    priority: -1,
  }),
  defineProductRule({
    id: "pleated-pants",
    group: "하의",
    detailCategory: "플리츠 팬츠",
    subCategory: "팬츠",
    keywords: ["플리츠 팬츠", "플리츠 슬랙스", "주름 팬츠", "pleated pants", "pleated trousers"],
    styleTags: ["미니멀", "모던"],
    priority: -1,
  }),
  defineProductRule({
    id: "gurkha-pants",
    group: "하의",
    detailCategory: "구르카 팬츠",
    subCategory: "팬츠",
    keywords: ["구르카 팬츠", "구르카 바지", "gurkha pants", "gurkha trousers"],
    styleTags: ["클래식", "아메카지"],
    priority: 20,
  }),
  defineProductRule({
    id: "fatigue-pants",
    group: "하의",
    detailCategory: "퍼티그 팬츠",
    subCategory: "팬츠",
    keywords: ["퍼티그 팬츠", "퍼티그 바지", "fatigue pants", "fatigue trousers"],
    styleTags: ["워크웨어", "아메카지"],
    priority: 20,
  }),
  defineProductRule({
    id: "baker-pants",
    group: "하의",
    detailCategory: "베이커 팬츠",
    subCategory: "팬츠",
    keywords: ["베이커 팬츠", "베이커 바지", "baker pants", "baker trousers"],
    styleTags: ["워크웨어", "아메카지"],
    priority: 20,
  }),
  defineProductRule({
    id: "corduroy-pants",
    group: "하의",
    detailCategory: "코듀로이 팬츠",
    subCategory: "팬츠",
    keywords: ["코듀로이 팬츠", "골덴 바지", "corduroy pants", "corduroy trousers"],
    material: "코듀로이",
    styleTags: ["클래식", "빈티지"],
    priority: 20,
  }),
  defineProductRule({
    id: "wool-pants",
    group: "하의",
    detailCategory: "울 팬츠",
    subCategory: "팬츠",
    keywords: ["울 팬츠", "모직 바지", "wool pants", "wool trousers"],
    material: "울",
    styleTags: ["클래식", "미니멀"],
    priority: 20,
  }),
  defineProductRule({
    id: "cropped-pants",
    group: "하의",
    detailCategory: "크롭 팬츠",
    subCategory: "팬츠",
    keywords: ["크롭 팬츠", "크롭트 팬츠", "cropped pants", "cropped trousers"],
    styleTags: ["모던", "미니멀"],
    priority: 20,
  }),
  defineProductRule({
    id: "ankle-pants",
    group: "하의",
    detailCategory: "앵클 팬츠",
    subCategory: "팬츠",
    keywords: ["앵클 팬츠", "발목 팬츠", "ankle pants", "ankle length trousers"],
    styleTags: ["미니멀", "데일리"],
    priority: 20,
  }),
  defineProductRule({
    id: "painter-pants",
    group: "하의",
    detailCategory: "페인터 팬츠",
    subCategory: "팬츠",
    keywords: ["페인터 팬츠", "페인터 바지", "painter pants", "painter trousers"],
    styleTags: ["워크웨어", "아메카지"],
    priority: 20,
  }),
  defineProductRule({
    id: "utility-pants",
    group: "하의",
    detailCategory: "유틸리티 팬츠",
    subCategory: "팬츠",
    keywords: ["유틸리티 팬츠", "유틸리티 바지", "utility pants", "utility trousers"],
    styleTags: ["워크웨어", "고프코어"],
    priority: 20,
  }),
  defineProductRule({
    id: "side-line-pants",
    group: "하의",
    detailCategory: "사이드라인 팬츠",
    subCategory: "팬츠",
    keywords: ["사이드라인 팬츠", "사이드 라인 팬츠", "side line pants", "side stripe pants"],
    styleTags: ["스포티", "캐주얼"],
    priority: 25,
  }),
  defineProductRule({
    id: "track-pants",
    group: "하의",
    detailCategory: "트랙 팬츠",
    subCategory: "팬츠",
    keywords: ["트랙 팬츠", "트랙팬츠", "track pants", "track trousers"],
    styleTags: ["스포티", "편안함"],
    priority: 20,
  }),
  defineProductRule({
    id: "denim-shorts",
    group: "하의",
    detailCategory: "데님 쇼츠",
    subCategory: "반바지",
    keywords: ["데님 쇼츠", "데님 반바지", "denim shorts", "jean shorts"],
    material: "데님",
    styleTags: ["캐주얼", "데일리"],
    priority: 0,
  }),
  defineProductRule({
    id: "cargo-shorts",
    group: "하의",
    detailCategory: "카고 쇼츠",
    subCategory: "반바지",
    keywords: ["카고 쇼츠", "카고 반바지", "cargo shorts", "cargo short pants"],
    styleTags: ["고프코어", "스트릿"],
    priority: 25,
  }),
  defineProductRule({
    id: "chino-shorts",
    group: "하의",
    detailCategory: "치노 쇼츠",
    subCategory: "반바지",
    keywords: ["치노 쇼츠", "치노 반바지", "chino shorts", "chino short pants"],
    styleTags: ["미니멀", "데일리"],
    priority: 25,
  }),
  defineProductRule({
    id: "sweat-shorts",
    group: "하의",
    detailCategory: "스웨트 쇼츠",
    subCategory: "반바지",
    keywords: ["스웨트 쇼츠", "스웨트 반바지", "sweat shorts", "sweatshorts"],
    styleTags: ["캐주얼", "편안함"],
    priority: 25,
  }),
  defineProductRule({
    id: "training-shorts",
    group: "하의",
    detailCategory: "트레이닝 쇼츠",
    subCategory: "반바지",
    keywords: ["트레이닝 쇼츠", "트레이닝 반바지", "training shorts", "workout shorts"],
    styleTags: ["스포티", "편안함"],
    priority: 25,
  }),
  defineProductRule({
    id: "cycling-shorts",
    group: "하의",
    detailCategory: "사이클링 쇼츠",
    subCategory: "반바지",
    keywords: ["사이클링 쇼츠", "바이커 쇼츠", "cycling shorts", "biker shorts"],
    styleTags: ["스포티", "모던"],
    priority: 25,
  }),
  defineProductRule({
    id: "pencil-skirt",
    group: "하의",
    detailCategory: "펜슬 스커트",
    subCategory: "스커트",
    keywords: ["펜슬 스커트", "펜슬스커트", "pencil skirt", "pencil skirts"],
    styleTags: ["포멀", "페미닌"],
    priority: 20,
  }),
  defineProductRule({
    id: "mermaid-skirt",
    group: "하의",
    detailCategory: "머메이드 스커트",
    subCategory: "스커트",
    keywords: ["머메이드 스커트", "머메이드스커트", "mermaid skirt", "fishtail skirt"],
    styleTags: ["페미닌", "모던"],
    priority: 20,
  }),
  defineProductRule({
    id: "wrap-skirt",
    group: "하의",
    detailCategory: "랩 스커트",
    subCategory: "스커트",
    keywords: ["랩 스커트", "랩스커트", "wrap skirt", "wrapped skirt"],
    styleTags: ["페미닌", "데일리"],
    priority: 20,
  }),
  defineProductRule({
    id: "cargo-skirt",
    group: "하의",
    detailCategory: "카고 스커트",
    subCategory: "스커트",
    keywords: ["카고 스커트", "카고스커트", "cargo skirt", "utility cargo skirt"],
    styleTags: ["스트릿", "고프코어"],
    priority: 20,
  }),
  defineProductRule({
    id: "tiered-skirt",
    group: "하의",
    detailCategory: "티어드 스커트",
    subCategory: "스커트",
    keywords: ["티어드 스커트", "캉캉 스커트", "tiered skirt", "tier skirt"],
    styleTags: ["러블리", "페미닌"],
    priority: 20,
  }),
  defineProductRule({
    id: "tennis-skirt",
    group: "하의",
    detailCategory: "테니스 스커트",
    subCategory: "스커트",
    keywords: ["테니스 스커트", "테니스스커트", "tennis skirt", "tennis skirts"],
    styleTags: ["스포티", "캐주얼"],
    priority: 20,
  }),
  defineProductRule({
    id: "flare-skirt",
    group: "하의",
    detailCategory: "플레어 스커트",
    subCategory: "스커트",
    keywords: ["플레어 스커트", "플레어스커트", "flare skirt", "flared skirt"],
    styleTags: ["페미닌", "클래식"],
    priority: 20,
  }),
  defineProductRule({
    id: "balloon-skirt",
    group: "하의",
    detailCategory: "벌룬 스커트",
    subCategory: "스커트",
    keywords: ["벌룬 스커트", "벌룬스커트", "balloon skirt", "bubble skirt"],
    styleTags: ["모던", "러블리"],
    priority: 20,
  }),
  defineProductRule({
    id: "slit-skirt",
    group: "하의",
    detailCategory: "슬릿 스커트",
    subCategory: "스커트",
    keywords: ["슬릿 스커트", "트임 스커트", "slit skirt", "split skirt"],
    styleTags: ["모던", "페미닌"],
    priority: 20,
  }),
  {
    id: "balloon-pants",
    group: "하의",
    label: "벌룬 팬츠",
    keywords: [
      "벌룬 팬츠",
      "벌룬팬츠",
      "벌룬 핏 팬츠",
      "벌룬핏 팬츠",
      "볼륨 팬츠",
      "볼륨팬츠",
      "balloon pants",
      "balloon fit pants",
      "volume pants",
    ],
    priority: 30,
    attributes: {
      category: "하의",
      subCategory: "팬츠",
      detailCategory: "벌룬 팬츠",
      styleTags: ["캐주얼", "스트릿"],
    },
  },
  {
    id: "barrel-pants",
    group: "하의",
    label: "배럴 팬츠",
    keywords: [
      "배럴 팬츠",
      "배럴팬츠",
      "배럴 레그 팬츠",
      "배럴레그 팬츠",
      "barrel pants",
      "barrel leg pants",
    ],
    priority: 30,
    attributes: {
      category: "하의",
      subCategory: "팬츠",
      detailCategory: "배럴 팬츠",
      styleTags: ["캐주얼", "모던"],
    },
  },
  {
    id: "curved-pants",
    group: "하의",
    label: "커브드 팬츠",
    keywords: [
      "커브드 팬츠",
      "커브 팬츠",
      "커브드핏 팬츠",
      "커브드 핏 팬츠",
      "curved pants",
      "curve pants",
      "curved fit pants",
    ],
    priority: 30,
    attributes: {
      category: "하의",
      subCategory: "팬츠",
      detailCategory: "커브드 팬츠",
      styleTags: ["캐주얼", "미니멀"],
    },
  },
  {
    id: "bootcut-pants",
    group: "하의",
    label: "부츠컷 팬츠",
    keywords: [
      "부츠컷 팬츠",
      "부츠컷팬츠",
      "부츠컷 바지",
      "bootcut pants",
      "boot cut pants",
    ],
    attributes: {
      category: "하의",
      subCategory: "팬츠",
      detailCategory: "부츠컷 팬츠",
      styleTags: ["캐주얼", "모던"],
    },
  },
  {
    id: "flare-pants",
    group: "하의",
    label: "플레어 팬츠",
    keywords: [
      "플레어 팬츠",
      "플레어팬츠",
      "나팔 바지",
      "나팔바지",
      "flare pants",
      "flared pants",
    ],
    attributes: {
      category: "하의",
      subCategory: "팬츠",
      detailCategory: "플레어 팬츠",
      styleTags: ["모던", "페미닌"],
    },
  },
  {
    id: "tapered-pants",
    group: "하의",
    label: "테이퍼드 팬츠",
    keywords: [
      "테이퍼드 팬츠",
      "테이퍼드팬츠",
      "테이퍼 핏 팬츠",
      "tapered pants",
      "tapered fit pants",
    ],
    attributes: {
      category: "하의",
      subCategory: "팬츠",
      detailCategory: "테이퍼드 팬츠",
      styleTags: ["미니멀", "데일리"],
    },
  },
  {
    id: "skinny-pants",
    group: "하의",
    label: "스키니 팬츠",
    keywords: ["스키니 팬츠", "스키니팬츠", "스키니 진", "skinny pants", "skinny jeans"],
    attributes: {
      category: "하의",
      subCategory: "팬츠",
      detailCategory: "스키니 팬츠",
      styleTags: ["캐주얼", "데일리"],
    },
  },
  {
    id: "slim-pants",
    group: "하의",
    label: "슬림 팬츠",
    keywords: [
      "슬림 팬츠",
      "슬림팬츠",
      "슬림핏 팬츠",
      "슬림 핏 팬츠",
      "slim pants",
      "slim fit pants",
    ],
    attributes: {
      category: "하의",
      subCategory: "팬츠",
      detailCategory: "슬림 팬츠",
      styleTags: ["미니멀", "데일리"],
    },
  },
  {
    id: "jeggings",
    group: "하의",
    label: "제깅스",
    keywords: ["제깅스", "denim jeggings", "jeggings"],
    attributes: {
      category: "하의",
      subCategory: "팬츠",
      detailCategory: "제깅스",
      material: "데님",
      styleTags: ["캐주얼", "데일리"],
    },
  },
  {
    id: "leggings",
    group: "하의",
    label: "레깅스",
    keywords: ["레깅스", "요가 팬츠", "요가 레깅스", "leggings", "yoga pants"],
    attributes: {
      category: "하의",
      subCategory: "팬츠",
      detailCategory: "레깅스",
      styleTags: ["스포티", "편안함"],
    },
  },
  {
    id: "capri-pants",
    group: "하의",
    label: "카프리 팬츠",
    keywords: [
      "카프리 팬츠",
      "카프리팬츠",
      "7부 팬츠",
      "칠부 팬츠",
      "capri pants",
      "capris",
    ],
    attributes: {
      category: "하의",
      subCategory: "팬츠",
      detailCategory: "카프리 팬츠",
      styleTags: ["캐주얼", "데일리"],
    },
  },
  {
    id: "culotte-pants",
    group: "하의",
    label: "큐롯 팬츠",
    keywords: ["큐롯 팬츠", "큐롯팬츠", "큐롯", "culotte pants", "culottes"],
    attributes: {
      category: "하의",
      subCategory: "팬츠",
      detailCategory: "큐롯 팬츠",
      styleTags: ["미니멀", "캐주얼"],
    },
  },
  {
    id: "pleated-skirt",
    group: "하의",
    label: "플리츠 스커트",
    keywords: [
      "플리츠 스커트",
      "플리츠스커트",
      "플리츠 미니 스커트",
      "플리츠 미디 스커트",
      "플리츠 롱 스커트",
      "pleated skirt",
      "pleated mini skirt",
      "pleated midi skirt",
      "pleated maxi skirt",
      "pleats skirt",
    ],
    attributes: {
      category: "하의",
      subCategory: "스커트",
      detailCategory: "플리츠 스커트",
      styleTags: ["클래식", "페미닌"],
    },
  },
  {
    id: "a-line-skirt",
    group: "하의",
    label: "A라인 스커트",
    keywords: ["A라인 스커트", "A라인스커트", "A-line skirt", "aline skirt"],
    attributes: {
      category: "하의",
      subCategory: "스커트",
      detailCategory: "A라인 스커트",
      styleTags: ["페미닌", "데일리"],
    },
  },
  {
    id: "mini-skirt",
    group: "하의",
    label: "미니 스커트",
    keywords: ["미니 스커트", "미니스커트", "mini skirt"],
    attributes: {
      category: "하의",
      subCategory: "스커트",
      detailCategory: "미니 스커트",
      styleTags: ["캐주얼", "데일리"],
    },
  },
  {
    id: "midi-skirt",
    group: "하의",
    label: "미디 스커트",
    keywords: ["미디 스커트", "미디스커트", "midi skirt"],
    attributes: {
      category: "하의",
      subCategory: "스커트",
      detailCategory: "미디 스커트",
      styleTags: ["미니멀", "데일리"],
    },
  },
  {
    id: "long-skirt",
    group: "하의",
    label: "롱 스커트",
    keywords: [
      "롱 스커트",
      "롱스커트",
      "맥시 스커트",
      "맥시스커트",
      "long skirt",
      "maxi skirt",
    ],
    attributes: {
      category: "하의",
      subCategory: "스커트",
      detailCategory: "롱 스커트",
      styleTags: ["미니멀", "데일리"],
    },
  },
  {
    id: "denim-skirt",
    group: "하의",
    label: "데님 스커트",
    keywords: ["데님 스커트", "데님스커트", "청치마", "denim skirt"],
    attributes: {
      category: "하의",
      subCategory: "스커트",
      detailCategory: "데님 스커트",
      material: "데님",
      styleTags: ["캐주얼", "데일리"],
    },
  },
  {
    id: "wide-slacks",
    group: "하의",
    label: "와이드 슬랙스",
    keywords: ["와이드 슬랙스", "wide slacks", "wide trousers"],
    attributes: {
      category: "하의",
      subCategory: "슬랙스",
      detailCategory: "와이드 슬랙스",
      styleTags: ["미니멀", "모던"],
    },
  },
  {
    id: "wide-denim",
    group: "하의",
    label: "와이드 데님",
    keywords: ["와이드 데님", "와이드 청바지", "wide denim", "wide jeans"],
    attributes: {
      category: "하의",
      subCategory: "데님팬츠",
      detailCategory: "와이드 데님 팬츠",
      material: "데님",
      styleTags: ["캐주얼", "스트릿"],
    },
  },
  {
    id: "wide-pants",
    group: "하의",
    label: "와이드 팬츠",
    keywords: [
      "와이드 팬츠",
      "와이드팬츠",
      "와이드핏 팬츠",
      "와이드 핏 팬츠",
      "wide pants",
      "wide fit pants",
    ],
    attributes: {
      category: "하의",
      subCategory: "팬츠",
      detailCategory: "와이드 팬츠",
      styleTags: ["캐주얼", "미니멀"],
    },
  },
  {
    id: "straight-denim",
    group: "하의",
    label: "스트레이트 데님",
    keywords: ["스트레이트 데님", "일자 데님", "straight denim", "straight jeans"],
    attributes: {
      category: "하의",
      subCategory: "데님팬츠",
      detailCategory: "스트레이트 데님 팬츠",
      material: "데님",
      styleTags: ["캐주얼", "데일리"],
    },
  },
  {
    id: "raw-denim",
    group: "하의",
    label: "생지 데님",
    keywords: ["생지 데님", "생지 청바지", "raw denim", "rigid denim"],
    attributes: {
      category: "하의",
      subCategory: "데님팬츠",
      detailCategory: "생지 데님 팬츠",
      material: "데님",
      styleTags: ["아메카지", "클래식"],
    },
  },
  {
    id: "washed-denim",
    group: "하의",
    label: "워싱 데님",
    keywords: ["워싱 데님", "워싱 청바지", "washed denim", "washed jeans"],
    attributes: {
      category: "하의",
      subCategory: "데님팬츠",
      detailCategory: "워싱 데님 팬츠",
      material: "데님",
      styleTags: ["캐주얼", "빈티지"],
    },
  },
  {
    id: "cargo-pants",
    group: "하의",
    label: "카고 팬츠",
    keywords: ["카고 팬츠", "카고팬츠", "cargo pants", "cargo trousers"],
    attributes: {
      category: "하의",
      subCategory: "팬츠",
      detailCategory: "카고 팬츠",
      styleTags: ["고프코어", "스트릿"],
    },
  },
  {
    id: "jogger-pants",
    group: "하의",
    label: "조거 팬츠",
    keywords: ["조거 팬츠", "조거팬츠", "jogger pants", "joggers"],
    attributes: {
      category: "하의",
      subCategory: "팬츠",
      detailCategory: "조거 팬츠",
      styleTags: ["스포티", "편안함"],
    },
  },
  {
    id: "chino-pants",
    group: "하의",
    label: "치노 팬츠",
    keywords: ["치노 팬츠", "치노팬츠", "chino pants", "chinos"],
    attributes: {
      category: "하의",
      subCategory: "팬츠",
      detailCategory: "치노 팬츠",
      styleTags: ["미니멀", "데일리"],
    },
  },
  {
    id: "carpenter-pants",
    group: "하의",
    label: "카펜터 팬츠",
    keywords: ["카펜터 팬츠", "카펜터팬츠", "carpenter pants"],
    attributes: {
      category: "하의",
      subCategory: "팬츠",
      detailCategory: "카펜터 팬츠",
      styleTags: ["워크웨어", "아메카지"],
    },
  },
  {
    id: "parachute-pants",
    group: "하의",
    label: "파라슈트 팬츠",
    keywords: ["파라슈트 팬츠", "파라슈트팬츠", "parachute pants"],
    attributes: {
      category: "하의",
      subCategory: "팬츠",
      detailCategory: "파라슈트 팬츠",
      styleTags: ["스트릿", "고프코어"],
    },
  },
  {
    id: "training-pants",
    group: "하의",
    label: "트레이닝 팬츠",
    keywords: ["트레이닝 팬츠", "트레이닝팬츠", "sweatpants", "sweat pants"],
    attributes: {
      category: "하의",
      subCategory: "팬츠",
      detailCategory: "트레이닝 팬츠",
      styleTags: ["스포티", "편안함"],
    },
  },
  {
    id: "bermuda-shorts",
    group: "하의",
    label: "버뮤다 쇼츠",
    keywords: [
      "버뮤다 팬츠",
      "버뮤다 쇼츠",
      "버뮤다 반바지",
      "bermuda pants",
      "bermuda shorts",
      "bermuda",
    ],
    priority: 10,
    attributes: {
      category: "하의",
      subCategory: "반바지",
      detailCategory: "버뮤다 쇼츠",
      styleTags: ["캐주얼", "미니멀"],
    },
  },
  {
    id: "shorts",
    group: "하의",
    label: "반바지",
    keywords: ["반바지", "쇼츠", "shorts", "short pants"],
    attributes: {
      category: "하의",
      subCategory: "반바지",
      detailCategory: "반바지",
      styleTags: ["캐주얼", "편안함"],
    },
  },
  {
    id: "denim-pants",
    group: "하의",
    label: "데님 팬츠",
    keywords: ["데님 팬츠", "denim pants", "denim jeans", "청바지", "jeans"],
    attributes: {
      category: "하의",
      subCategory: "팬츠",
      detailCategory: "데님 팬츠",
      material: "데님",
      styleTags: ["캐주얼", "데일리"],
    },
  },
  {
    id: "linen-pants",
    group: "하의",
    label: "린넨 팬츠",
    keywords: ["린넨 팬츠", "linen pants", "linen trousers"],
    attributes: {
      category: "하의",
      subCategory: "팬츠",
      detailCategory: "린넨 팬츠",
      material: "린넨",
      styleTags: ["미니멀", "데일리"],
    },
  },
  {
    id: "slacks",
    group: "하의",
    label: "슬랙스",
    keywords: ["슬랙스", "slacks", "tailored trousers"],
    attributes: {
      category: "하의",
      subCategory: "팬츠",
      detailCategory: "슬랙스",
      styleTags: ["미니멀", "포멀"],
    },
  },
  {
    id: "baggy-pants",
    group: "하의",
    label: "배기 팬츠",
    keywords: [
      "배기 팬츠",
      "배기팬츠",
      "배기 바지",
      "baggy pants",
      "baggy trousers",
    ],
    attributes: {
      category: "하의",
      subCategory: "팬츠",
      detailCategory: "배기 팬츠",
      styleTags: ["캐주얼", "스트릿"],
    },
  },
  {
    id: "loose-pants",
    group: "하의",
    label: "루즈 팬츠",
    keywords: [
      "루즈 핏 팬츠",
      "루즈핏 팬츠",
      "루즈 팬츠",
      "loose fit pants",
      "loose pants",
      "relaxed fit pants",
      "relaxed pants",
    ],
    attributes: {
      category: "하의",
      subCategory: "팬츠",
      detailCategory: "루즈 팬츠",
      styleTags: ["캐주얼", "편안함"],
    },
  },
  {
    id: "straight-pants",
    group: "하의",
    label: "스트레이트 팬츠",
    keywords: [
      "스트레이트 팬츠",
      "스트레이트핏 팬츠",
      "스트레이트 핏 팬츠",
      "일자 팬츠",
      "일자 바지",
      "straight pants",
      "straight fit pants",
      "straight trousers",
    ],
    attributes: {
      category: "하의",
      subCategory: "팬츠",
      detailCategory: "스트레이트 팬츠",
      styleTags: ["캐주얼", "데일리"],
    },
  },
  defineProductRule({
    id: "low-top-sneakers",
    group: "신발",
    detailCategory: "로우탑 스니커즈",
    subCategory: "스니커즈",
    keywords: ["로우탑 스니커즈", "로우탑 운동화", "low top sneakers", "low-top sneaker"],
    styleTags: ["캐주얼", "데일리"],
    priority: 20,
  }),
  defineProductRule({
    id: "high-top-sneakers",
    group: "신발",
    detailCategory: "하이탑 스니커즈",
    subCategory: "스니커즈",
    keywords: ["하이탑 스니커즈", "하이탑 운동화", "high top sneakers", "high-top sneaker"],
    styleTags: ["캐주얼", "스트릿"],
    priority: 25,
  }),
  defineProductRule({
    id: "canvas-sneakers",
    group: "신발",
    detailCategory: "캔버스 스니커즈",
    subCategory: "스니커즈",
    keywords: ["캔버스 스니커즈", "캔버스화", "canvas sneakers", "canvas shoes"],
    styleTags: ["캐주얼", "데일리"],
    priority: 20,
  }),
  defineProductRule({
    id: "court-sneakers",
    group: "신발",
    detailCategory: "코트 스니커즈",
    subCategory: "스니커즈",
    keywords: ["코트 스니커즈", "테니스 코트화", "court sneakers", "court shoes"],
    styleTags: ["미니멀", "캐주얼"],
    priority: 20,
  }),
  defineProductRule({
    id: "german-army-sneakers",
    group: "신발",
    detailCategory: "독일군 스니커즈",
    subCategory: "스니커즈",
    keywords: ["독일군 스니커즈", "독일군 운동화", "german army sneakers", "german trainer sneakers"],
    styleTags: ["미니멀", "클래식"],
    priority: 25,
  }),
  defineProductRule({
    id: "retro-runner",
    group: "신발",
    detailCategory: "레트로 러너",
    subCategory: "스니커즈",
    keywords: ["레트로 러너", "레트로 러닝화", "retro runner", "retro runner sneakers"],
    styleTags: ["캐주얼", "스포티"],
    priority: 25,
  }),
  defineProductRule({
    id: "chunky-sneakers",
    group: "신발",
    detailCategory: "청키 스니커즈",
    subCategory: "스니커즈",
    keywords: ["청키 스니커즈", "어글리 슈즈", "chunky sneakers", "dad sneakers"],
    styleTags: ["스트릿", "캐주얼"],
    priority: 20,
  }),
  defineProductRule({
    id: "platform-sneakers",
    group: "신발",
    detailCategory: "플랫폼 스니커즈",
    subCategory: "스니커즈",
    keywords: ["플랫폼 스니커즈", "통굽 스니커즈", "platform sneakers", "platform trainers"],
    styleTags: ["모던", "캐주얼"],
    priority: 20,
  }),
  defineProductRule({
    id: "slip-on",
    group: "신발",
    detailCategory: "슬립온",
    subCategory: "스니커즈",
    keywords: ["슬립온", "슬립 온", "slip on shoes", "slip-on sneakers"],
    styleTags: ["캐주얼", "편안함"],
    priority: 20,
  }),
  defineProductRule({
    id: "skate-shoes",
    group: "신발",
    detailCategory: "스케이트 슈즈",
    subCategory: "스니커즈",
    keywords: ["스케이트 슈즈", "스케이트화", "skate shoes", "skate sneakers"],
    styleTags: ["스트릿", "캐주얼"],
    priority: 20,
  }),
  defineProductRule({
    id: "walking-shoes",
    group: "신발",
    detailCategory: "워킹화",
    subCategory: "운동화",
    keywords: ["워킹화", "워킹 슈즈", "walking shoes", "walking sneakers"],
    styleTags: ["스포티", "편안함"],
    priority: 20,
  }),
  defineProductRule({
    id: "trail-running-shoes",
    group: "신발",
    detailCategory: "트레일 러닝화",
    subCategory: "운동화",
    keywords: ["트레일 러닝화", "트레일 러닝 슈즈", "트레일런닝화", "trail running shoes", "trail runners"],
    styleTags: ["고프코어", "스포티"],
    priority: 30,
  }),
  defineProductRule({
    id: "hiking-shoes",
    group: "신발",
    detailCategory: "하이킹화",
    subCategory: "운동화",
    keywords: ["하이킹화", "하이킹 슈즈", "hiking shoes", "hiking footwear"],
    styleTags: ["고프코어", "스포티"],
    priority: 20,
  }),
  defineProductRule({
    id: "trekking-shoes",
    group: "신발",
    detailCategory: "트레킹화",
    subCategory: "운동화",
    keywords: ["트레킹화", "트레킹 슈즈", "trekking shoes", "trekking footwear"],
    excludedKeywords: ["팬츠", "바지", "pants", "trousers"],
    styleTags: ["고프코어", "스포티"],
    priority: 20,
  }),
  defineProductRule({
    id: "training-shoes",
    group: "신발",
    detailCategory: "트레이닝화",
    subCategory: "운동화",
    keywords: ["트레이닝화", "트레이닝 슈즈", "training shoes", "cross training shoes"],
    styleTags: ["스포티", "편안함"],
    priority: 20,
  }),
  defineProductRule({
    id: "basketball-shoes",
    group: "신발",
    detailCategory: "농구화",
    subCategory: "운동화",
    keywords: ["농구화", "농구 슈즈", "basketball shoes", "basketball sneakers"],
    styleTags: ["스포티", "스트릿"],
    priority: 20,
  }),
  defineProductRule({
    id: "tennis-shoes",
    group: "신발",
    detailCategory: "테니스화",
    subCategory: "운동화",
    keywords: ["테니스화", "테니스 슈즈", "tennis shoes", "tennis sneakers"],
    styleTags: ["스포티", "캐주얼"],
    priority: 20,
  }),
  defineProductRule({
    id: "soccer-shoes",
    group: "신발",
    detailCategory: "축구화",
    subCategory: "운동화",
    keywords: ["축구화", "풋살화", "soccer shoes", "football boots"],
    styleTags: ["스포티"],
    priority: 20,
  }),
  defineProductRule({
    id: "golf-shoes",
    group: "신발",
    detailCategory: "골프화",
    subCategory: "운동화",
    keywords: ["골프화", "골프 슈즈", "golf shoes", "golf footwear"],
    styleTags: ["스포티", "클래식"],
    priority: 20,
  }),
  defineProductRule({
    id: "oxford-shoes",
    group: "신발",
    detailCategory: "옥스포드화",
    subCategory: "구두",
    keywords: ["옥스포드화", "옥스포드 슈즈", "oxford shoes", "oxford dress shoes"],
    excludedKeywords: ["셔츠", "shirt"],
    styleTags: ["포멀", "클래식"],
    priority: 25,
  }),
  defineProductRule({
    id: "monk-strap",
    group: "신발",
    detailCategory: "몽크스트랩",
    subCategory: "구두",
    keywords: ["몽크스트랩", "몽크 스트랩", "monk strap shoes", "monkstrap shoes"],
    styleTags: ["포멀", "클래식"],
    priority: 25,
  }),
  defineProductRule({
    id: "brogue-shoes",
    group: "신발",
    detailCategory: "브로그 슈즈",
    subCategory: "구두",
    keywords: ["브로그 슈즈", "브로그화", "brogue shoes", "brogues"],
    styleTags: ["클래식", "포멀"],
    priority: 20,
  }),
  defineProductRule({
    id: "wingtip-shoes",
    group: "신발",
    detailCategory: "윙팁 슈즈",
    subCategory: "구두",
    keywords: ["윙팁 슈즈", "윙팁 구두", "wingtip shoes", "wing tip shoes"],
    styleTags: ["클래식", "포멀"],
    priority: 20,
  }),
  defineProductRule({
    id: "penny-loafers",
    group: "신발",
    detailCategory: "페니 로퍼",
    subCategory: "구두",
    keywords: ["페니 로퍼", "페니로퍼", "penny loafers", "penny loafer"],
    styleTags: ["클래식", "미니멀"],
    priority: 25,
  }),
  defineProductRule({
    id: "tassel-loafers",
    group: "신발",
    detailCategory: "태슬 로퍼",
    subCategory: "구두",
    keywords: ["태슬 로퍼", "테슬 로퍼", "tassel loafers", "tassel loafer"],
    styleTags: ["클래식", "포멀"],
    priority: 25,
  }),
  defineProductRule({
    id: "horsebit-loafers",
    group: "신발",
    detailCategory: "홀스빗 로퍼",
    subCategory: "구두",
    keywords: ["홀스빗 로퍼", "비트 로퍼", "horsebit loafers", "bit loafer"],
    styleTags: ["클래식", "포멀"],
    priority: 25,
  }),
  defineProductRule({
    id: "driving-shoes",
    group: "신발",
    detailCategory: "드라이빙 슈즈",
    subCategory: "구두",
    keywords: ["드라이빙 슈즈", "드라이빙 로퍼", "driving shoes", "driving loafers"],
    styleTags: ["캐주얼", "클래식"],
    priority: 20,
  }),
  defineProductRule({
    id: "pumps",
    group: "신발",
    detailCategory: "펌프스",
    subCategory: "구두",
    keywords: ["펌프스", "펌프스 힐", "pumps shoes", "court pumps"],
    styleTags: ["포멀", "페미닌"],
    priority: 20,
  }),
  defineProductRule({
    id: "mary-jane-shoes",
    group: "신발",
    detailCategory: "메리제인 슈즈",
    subCategory: "구두",
    keywords: ["메리제인 슈즈", "메리제인 플랫", "mary jane shoes", "mary jane flats"],
    styleTags: ["클래식", "러블리"],
    priority: 25,
  }),
  defineProductRule({
    id: "ballet-flats",
    group: "신발",
    detailCategory: "발레 플랫",
    subCategory: "구두",
    keywords: ["발레 플랫", "발레리나 플랫", "ballet flats", "ballet shoes"],
    styleTags: ["페미닌", "미니멀"],
    priority: 25,
  }),
  defineProductRule({
    id: "flat-shoes",
    group: "신발",
    detailCategory: "플랫 슈즈",
    subCategory: "구두",
    keywords: ["플랫 슈즈", "플랫화", "flat shoes", "flat footwear"],
    styleTags: ["미니멀", "페미닌"],
    priority: 15,
  }),
  defineProductRule({
    id: "kitten-heels",
    group: "신발",
    detailCategory: "키튼힐",
    subCategory: "구두",
    keywords: ["키튼힐", "키튼 힐", "kitten heels", "kitten heel shoes"],
    styleTags: ["페미닌", "포멀"],
    priority: 20,
  }),
  defineProductRule({
    id: "stiletto-heels",
    group: "신발",
    detailCategory: "스틸레토 힐",
    subCategory: "구두",
    keywords: ["스틸레토 힐", "스틸레토힐", "stiletto heels", "stiletto pumps"],
    styleTags: ["포멀", "페미닌"],
    priority: 20,
  }),
  defineProductRule({
    id: "block-heels",
    group: "신발",
    detailCategory: "블록힐",
    subCategory: "구두",
    keywords: ["블록힐", "블록 힐", "block heels", "block heel shoes"],
    styleTags: ["모던", "페미닌"],
    priority: 20,
  }),
  defineProductRule({
    id: "ankle-boots",
    group: "신발",
    detailCategory: "앵클부츠",
    subCategory: "부츠",
    keywords: ["앵클부츠", "앵클 부츠", "ankle boots", "ankle boot"],
    styleTags: ["클래식", "모던"],
    priority: 25,
  }),
  defineProductRule({
    id: "combat-boots",
    group: "신발",
    detailCategory: "컴뱃부츠",
    subCategory: "부츠",
    keywords: ["컴뱃부츠", "컴뱃 부츠", "combat boots", "combat boot"],
    styleTags: ["스트릿", "고프코어"],
    priority: 25,
  }),
  defineProductRule({
    id: "work-boots",
    group: "신발",
    detailCategory: "워크부츠",
    subCategory: "부츠",
    keywords: ["워크부츠", "워크 부츠", "work boots", "work boot"],
    styleTags: ["워크웨어", "아메카지"],
    priority: 25,
  }),
  defineProductRule({
    id: "lace-up-boots",
    group: "신발",
    detailCategory: "레이스업 부츠",
    subCategory: "부츠",
    keywords: ["레이스업 부츠", "끈 부츠", "lace up boots"],
    styleTags: ["클래식", "캐주얼"],
    priority: 25,
  }),
  defineProductRule({
    id: "chukka-boots",
    group: "신발",
    detailCategory: "처카부츠",
    subCategory: "부츠",
    keywords: ["처카부츠", "처카 부츠", "chukka boots", "chukka boot"],
    styleTags: ["클래식", "캐주얼"],
    priority: 25,
  }),
  defineProductRule({
    id: "desert-boots",
    group: "신발",
    detailCategory: "데저트부츠",
    subCategory: "부츠",
    keywords: ["데저트부츠", "데저트 부츠", "desert boots", "desert boot"],
    styleTags: ["클래식", "캐주얼"],
    priority: 25,
  }),
  defineProductRule({
    id: "engineer-boots",
    group: "신발",
    detailCategory: "엔지니어 부츠",
    subCategory: "부츠",
    keywords: ["엔지니어 부츠", "엔지니어부츠", "engineer boots", "engineer boot"],
    styleTags: ["워크웨어", "빈티지"],
    priority: 25,
  }),
  defineProductRule({
    id: "western-boots",
    group: "신발",
    detailCategory: "웨스턴 부츠",
    subCategory: "부츠",
    keywords: ["웨스턴 부츠", "웨스턴부츠", "western boots", "western boot"],
    styleTags: ["빈티지", "아메카지"],
    priority: 25,
  }),
  defineProductRule({
    id: "cowboy-boots",
    group: "신발",
    detailCategory: "카우보이 부츠",
    subCategory: "부츠",
    keywords: ["카우보이 부츠", "카우보이부츠", "cowboy boots", "cowboy boot"],
    styleTags: ["빈티지", "아메카지"],
    priority: 25,
  }),
  defineProductRule({
    id: "mid-boots",
    group: "신발",
    detailCategory: "미들부츠",
    subCategory: "부츠",
    keywords: ["미들부츠", "미들 부츠", "mid boots", "mid calf boots"],
    styleTags: ["모던", "캐주얼"],
    priority: 20,
  }),
  defineProductRule({
    id: "long-boots",
    group: "신발",
    detailCategory: "롱부츠",
    subCategory: "부츠",
    keywords: ["롱부츠", "롱 부츠", "long boots", "knee high boots"],
    styleTags: ["모던", "클래식"],
    priority: 20,
  }),
  defineProductRule({
    id: "rain-boots",
    group: "신발",
    detailCategory: "레인부츠",
    subCategory: "부츠",
    keywords: ["레인부츠", "장화", "rain boots", "wellington boots"],
    styleTags: ["고프코어", "캐주얼"],
    priority: 25,
  }),
  defineProductRule({
    id: "snow-boots",
    group: "신발",
    detailCategory: "스노우부츠",
    subCategory: "부츠",
    keywords: ["스노우부츠", "방한 부츠", "snow boots", "winter boots"],
    styleTags: ["고프코어", "캐주얼"],
    priority: 25,
  }),
  defineProductRule({
    id: "fisherman-sandals",
    group: "신발",
    detailCategory: "피셔맨 샌들",
    subCategory: "샌들",
    keywords: ["피셔맨 샌들", "피셔맨샌들", "fisherman sandals", "fisherman sandal"],
    styleTags: ["캐주얼", "클래식"],
    priority: 30,
  }),
  defineProductRule({
    id: "sport-sandals",
    group: "신발",
    detailCategory: "스포츠 샌들",
    subCategory: "샌들",
    keywords: ["스포츠 샌들", "스포티 샌들", "sport sandals", "sports sandals"],
    styleTags: ["스포티", "고프코어"],
    priority: 25,
  }),
  defineProductRule({
    id: "strap-sandals",
    group: "신발",
    detailCategory: "스트랩 샌들",
    subCategory: "샌들",
    keywords: ["스트랩 샌들", "스트랩샌들", "strap sandals", "strappy sandals"],
    styleTags: ["캐주얼", "미니멀"],
    priority: 20,
  }),
  defineProductRule({
    id: "gladiator-sandals",
    group: "신발",
    detailCategory: "글래디에이터 샌들",
    subCategory: "샌들",
    keywords: ["글래디에이터 샌들", "글래디 샌들", "gladiator sandals", "gladiator sandal"],
    styleTags: ["빈티지", "모던"],
    priority: 25,
  }),
  defineProductRule({
    id: "platform-sandals",
    group: "신발",
    detailCategory: "플랫폼 샌들",
    subCategory: "샌들",
    keywords: ["플랫폼 샌들", "통굽 샌들", "platform sandals", "platform sandal"],
    styleTags: ["모던", "캐주얼"],
    priority: 25,
  }),
  defineProductRule({
    id: "slide-sandals",
    group: "신발",
    detailCategory: "슬라이드",
    subCategory: "슬리퍼",
    keywords: ["슬라이드", "슬라이드 샌들", "slide sandals", "slides footwear"],
    styleTags: ["캐주얼", "편안함"],
    priority: 20,
  }),
  defineProductRule({
    id: "flip-flops",
    group: "신발",
    detailCategory: "플립플롭",
    subCategory: "슬리퍼",
    keywords: ["플립플롭", "쪼리", "flip flops", "flip flop sandals"],
    styleTags: ["캐주얼", "편안함"],
    priority: 20,
  }),
  defineProductRule({
    id: "clogs",
    group: "신발",
    detailCategory: "클로그",
    subCategory: "슬리퍼",
    keywords: ["클로그", "클로그 뮬", "clog shoes", "clog mule"],
    styleTags: ["캐주얼", "편안함"],
    priority: 25,
  }),
  defineProductRule({
    id: "mules",
    group: "신발",
    detailCategory: "뮬",
    subCategory: "슬리퍼",
    keywords: ["뮬 슈즈", "뮬 슬리퍼", "mule shoes", "mules footwear"],
    styleTags: ["미니멀", "편안함"],
    priority: 20,
  }),
  {
    id: "slingback-shoes",
    group: "신발",
    label: "슬링백 슈즈",
    keywords: [
      "슬링백 슈즈",
      "슬링백 펌프스",
      "슬링백 힐",
      "슬링백 플랫",
      "slingback shoes",
      "slingback pumps",
      "slingback heels",
      "slingback flats",
    ],
    excludedKeywords: ["가방", "백", "bag"],
    priority: 30,
    attributes: {
      category: "신발",
      subCategory: "구두",
      detailCategory: "슬링백 슈즈",
      styleTags: ["미니멀", "포멀"],
    },
  },
  {
    id: "running-shoes",
    group: "신발",
    label: "러닝화",
    keywords: ["러닝화", "러닝 슈즈", "running shoes", "running sneakers"],
    excludedKeywords: ["자켓", "재킷", "바람막이", "jacket", "windbreaker"],
    attributes: {
      category: "신발",
      subCategory: "운동화",
      detailCategory: "러닝화",
      styleTags: ["스포티", "고프코어"],
    },
  },
  {
    id: "sneakers",
    group: "신발",
    label: "스니커즈",
    keywords: ["스니커즈", "운동화", "sneakers", "sneaker"],
    attributes: {
      category: "신발",
      subCategory: "스니커즈",
      detailCategory: "스니커즈",
      styleTags: ["캐주얼", "데일리"],
    },
  },
  {
    id: "derby-shoes",
    group: "신발",
    label: "더비슈즈",
    keywords: ["더비슈즈", "더비 슈즈", "더비화", "derby shoes"],
    attributes: {
      category: "신발",
      subCategory: "구두",
      detailCategory: "더비슈즈",
      styleTags: ["포멀", "클래식"],
    },
  },
  {
    id: "loafers",
    group: "신발",
    label: "로퍼",
    keywords: ["로퍼", "loafer", "loafers"],
    attributes: {
      category: "신발",
      subCategory: "구두",
      detailCategory: "로퍼",
      styleTags: ["미니멀", "포멀"],
    },
  },
  {
    id: "chelsea-boots",
    group: "신발",
    label: "첼시부츠",
    keywords: ["첼시부츠", "첼시 부츠", "chelsea boots", "chelsea boot"],
    attributes: {
      category: "신발",
      subCategory: "부츠",
      detailCategory: "첼시부츠",
      styleTags: ["클래식", "미니멀"],
    },
  },
  {
    id: "boots",
    group: "신발",
    label: "부츠",
    keywords: ["부츠", "워커", "boots", "boot"],
    excludedKeywords: ["부츠컷", "bootcut", "팬츠", "바지", "pants", "trousers"],
    attributes: {
      category: "신발",
      subCategory: "부츠",
      detailCategory: "부츠",
      styleTags: ["클래식", "캐주얼"],
    },
  },
  {
    id: "slippers",
    group: "신발",
    label: "슬리퍼",
    keywords: ["슬리퍼", "slippers", "slipper"],
    attributes: {
      category: "신발",
      subCategory: "슬리퍼",
      detailCategory: "슬리퍼",
      styleTags: ["캐주얼", "편안함"],
    },
  },
  {
    id: "sandals",
    group: "신발",
    label: "샌들",
    keywords: ["샌들", "sandal", "sandals"],
    attributes: {
      category: "신발",
      subCategory: "샌들",
      detailCategory: "샌들",
      styleTags: ["캐주얼", "편안함"],
    },
  },
  {
    id: "waist-bag",
    group: "가방",
    label: "웨이스트백",
    keywords: [
      "벨트 백",
      "벨트백",
      "웨이스트백",
      "웨이스트 백",
      "힙색",
      "힙 백",
      "waist bag",
      "belt bag",
      "fanny pack",
    ],
    attributes: {
      category: "액세서리",
      subCategory: "가방",
      detailCategory: "웨이스트백",
      styleTags: ["캐주얼", "고프코어"],
    },
  },
  {
    id: "messenger-bag",
    group: "가방",
    label: "메신저백",
    keywords: ["메신저백", "메신저 백", "messenger bag"],
    attributes: {
      category: "액세서리",
      subCategory: "가방",
      detailCategory: "메신저백",
      styleTags: ["스트릿", "캐주얼"],
    },
  },
  {
    id: "shoulder-bag",
    group: "가방",
    label: "숄더백",
    keywords: ["숄더백", "숄더 백", "shoulder bag"],
    attributes: {
      category: "액세서리",
      subCategory: "가방",
      detailCategory: "숄더백",
      styleTags: ["데일리", "미니멀"],
    },
  },
  {
    id: "sling-bag",
    group: "가방",
    label: "슬링백",
    keywords: ["슬링백", "슬링 백", "sling bag"],
    attributes: {
      category: "액세서리",
      subCategory: "가방",
      detailCategory: "슬링백",
      styleTags: ["스포티", "고프코어"],
    },
  },
  {
    id: "crossbody-bag",
    group: "가방",
    label: "크로스백",
    keywords: ["크로스백", "crossbody bag", "cross bag"],
    attributes: {
      category: "액세서리",
      subCategory: "가방",
      detailCategory: "크로스백",
      styleTags: ["캐주얼", "데일리"],
    },
  },
  {
    id: "tote-bag",
    group: "가방",
    label: "토트백",
    keywords: ["토트백", "tote bag"],
    attributes: {
      category: "액세서리",
      subCategory: "가방",
      detailCategory: "토트백",
      styleTags: ["미니멀", "데일리"],
    },
  },
  {
    id: "backpack",
    group: "가방",
    label: "백팩",
    keywords: ["백팩", "backpack", "rucksack"],
    attributes: {
      category: "액세서리",
      subCategory: "가방",
      detailCategory: "백팩",
      styleTags: ["캐주얼", "스포티"],
    },
  },
  {
    id: "bucket-hat",
    group: "모자",
    label: "버킷햇",
    keywords: ["버킷햇", "버킷 햇", "bucket hat"],
    attributes: {
      category: "액세서리",
      subCategory: "모자",
      detailCategory: "버킷햇",
      styleTags: ["캐주얼", "스트릿"],
    },
  },
  {
    id: "ball-cap",
    group: "모자",
    label: "볼캡",
    keywords: ["볼캡", "baseball cap", "ball cap"],
    attributes: {
      category: "액세서리",
      subCategory: "모자",
      detailCategory: "볼캡",
      styleTags: ["캐주얼", "스트릿"],
    },
  },
  {
    id: "beanie",
    group: "모자",
    label: "비니",
    keywords: ["비니", "beanie"],
    attributes: {
      category: "액세서리",
      subCategory: "모자",
      detailCategory: "비니",
      styleTags: ["캐주얼", "스트릿"],
    },
  },
  {
    id: "watch",
    group: "액세서리",
    label: "시계",
    keywords: ["손목시계", "시계", "wristwatch", "watch"],
    attributes: {
      category: "액세서리",
      subCategory: "시계",
      detailCategory: "시계",
      styleTags: ["클래식", "미니멀"],
    },
  },
  {
    id: "glasses",
    group: "액세서리",
    label: "안경",
    keywords: ["안경", "아이웨어", "glasses", "eyewear"],
    attributes: {
      category: "액세서리",
      subCategory: "안경",
      detailCategory: "안경",
      styleTags: ["미니멀", "클래식"],
    },
  },
  {
    id: "necklace",
    group: "액세서리",
    label: "목걸이",
    keywords: ["목걸이", "네크리스", "necklace"],
    attributes: {
      category: "액세서리",
      subCategory: "주얼리",
      detailCategory: "목걸이",
      styleTags: ["모던", "미니멀"],
    },
  },
  {
    id: "bracelet",
    group: "액세서리",
    label: "팔찌",
    keywords: ["팔찌", "브레이슬릿", "bracelet"],
    attributes: {
      category: "액세서리",
      subCategory: "주얼리",
      detailCategory: "팔찌",
      styleTags: ["모던", "미니멀"],
    },
  },
  {
    id: "ring",
    group: "액세서리",
    label: "반지",
    keywords: ["반지", "핑거 링", "finger ring"],
    attributes: {
      category: "액세서리",
      subCategory: "주얼리",
      detailCategory: "반지",
      styleTags: ["모던", "미니멀"],
    },
  },
  {
    id: "belt",
    group: "액세서리",
    label: "벨트",
    keywords: ["벨트", "belt"],
    attributes: {
      category: "액세서리",
      subCategory: "벨트",
      detailCategory: "벨트",
      styleTags: ["미니멀", "클래식"],
    },
  },
  {
    id: "scarf",
    group: "액세서리",
    label: "스카프",
    keywords: ["스카프", "머플러", "scarf", "muffler"],
    attributes: {
      category: "액세서리",
      subCategory: "스카프",
      detailCategory: "스카프",
      styleTags: ["클래식", "미니멀"],
    },
  },
];

// 세부 규칙이 없을 때만 사용하는 보수적인 기본 분류입니다.
export const PRODUCT_CATEGORY_FALLBACK_RULES: ProductClassificationRule[] = [
  {
    id: "generic-outerwear",
    group: "아우터",
    label: "아우터",
    keywords: ["아우터", "outerwear"],
    attributes: {
      category: "아우터",
      subCategory: "아우터",
      detailCategory: "아우터",
    },
  },
  {
    id: "generic-jacket",
    group: "아우터",
    label: "자켓",
    keywords: ["자켓", "재킷", "jacket", "jackets"],
    attributes: {
      category: "아우터",
      subCategory: "자켓",
      detailCategory: "자켓",
    },
  },
  {
    id: "generic-cardigan",
    group: "아우터",
    label: "가디건",
    keywords: ["가디건", "cardigan", "cardigans"],
    attributes: {
      category: "아우터",
      subCategory: "가디건",
      detailCategory: "가디건",
    },
  },
  {
    id: "generic-jumper",
    group: "아우터",
    label: "점퍼",
    keywords: ["점퍼", "jumper"],
    attributes: {
      category: "아우터",
      subCategory: "점퍼",
      detailCategory: "점퍼",
    },
  },
  {
    id: "generic-zip-up",
    group: "아우터",
    label: "집업",
    keywords: [
      "집업",
      "zip up",
      "zip-up",
      "zip sweatshirt",
      "zip-up sweatshirt",
      "sweat zip up",
    ],
    attributes: {
      category: "아우터",
      subCategory: "집업",
      detailCategory: "집업",
    },
  },
  {
    id: "generic-t-shirt",
    group: "상의",
    label: "티셔츠",
    keywords: ["티셔츠", "t shirt", "t-shirt"],
    attributes: {
      category: "상의",
      subCategory: "티셔츠",
      detailCategory: "티셔츠",
    },
  },
  {
    id: "generic-shirt",
    group: "상의",
    label: "셔츠",
    keywords: ["셔츠", "shirt", "shirts"],
    attributes: {
      category: "상의",
      subCategory: "셔츠",
      detailCategory: "셔츠",
    },
  },
  {
    id: "generic-blouse",
    group: "상의",
    label: "블라우스",
    keywords: ["블라우스", "blouse", "blouses"],
    attributes: {
      category: "상의",
      subCategory: "블라우스",
      detailCategory: "블라우스",
    },
  },
  {
    id: "generic-knit",
    group: "상의",
    label: "니트",
    keywords: ["니트", "knit", "sweater", "sweaters"],
    attributes: {
      category: "상의",
      subCategory: "니트",
      detailCategory: "니트",
      material: "니트",
    },
  },
  {
    id: "generic-sweatshirt",
    group: "상의",
    label: "맨투맨",
    keywords: ["맨투맨", "sweatshirt"],
    attributes: {
      category: "상의",
      subCategory: "맨투맨",
      detailCategory: "맨투맨",
    },
  },
  {
    id: "generic-hoodie",
    group: "상의",
    label: "후드티",
    keywords: ["후드", "hoodie", "hoodies"],
    attributes: {
      category: "상의",
      subCategory: "후드티",
      detailCategory: "후드티",
    },
  },
  {
    id: "generic-top",
    group: "상의",
    label: "상의",
    keywords: ["상의", "top", "tops"],
    attributes: {
      category: "상의",
      subCategory: "상의",
      detailCategory: "상의",
    },
  },
  {
    id: "generic-pants",
    group: "하의",
    label: "팬츠",
    keywords: [
      "팬츠",
      "바지",
      "레깅스",
      "제깅스",
      "pants",
      "trouser",
      "trousers",
      "leggings",
      "jeggings",
    ],
    attributes: {
      category: "하의",
      subCategory: "팬츠",
      detailCategory: "팬츠",
    },
  },
  {
    id: "generic-skirt",
    group: "하의",
    label: "스커트",
    keywords: ["스커트", "skirt", "skirts"],
    attributes: {
      category: "하의",
      subCategory: "스커트",
      detailCategory: "스커트",
    },
  },
  {
    id: "generic-bottom",
    group: "하의",
    label: "하의",
    keywords: ["하의", "bottom", "bottoms"],
    attributes: {
      category: "하의",
      subCategory: "하의",
      detailCategory: "하의",
    },
  },
  {
    id: "generic-bag",
    group: "가방",
    label: "가방",
    keywords: ["가방", "bag", "bags"],
    attributes: {
      category: "액세서리",
      subCategory: "가방",
      detailCategory: "가방",
    },
  },
  {
    id: "generic-shoes",
    group: "신발",
    label: "신발",
    keywords: ["신발", "shoes", "shoe", "footwear"],
    attributes: {
      category: "신발",
      subCategory: "신발",
      detailCategory: "신발",
    },
  },
  {
    id: "generic-hat",
    group: "모자",
    label: "모자",
    keywords: ["모자", "hat", "hats"],
    attributes: {
      category: "액세서리",
      subCategory: "모자",
      detailCategory: "모자",
    },
  },
  {
    id: "generic-accessory",
    group: "액세서리",
    label: "액세서리",
    keywords: ["액세서리", "accessory", "accessories"],
    attributes: {
      category: "액세서리",
      subCategory: "액세서리",
      detailCategory: "액세서리",
    },
  },
];
